### ISSUE TITLE
Search thread failed. Response dictionary key error

### ISSUE THREAD

**Issue by mkorsak** [AHAAAAAAA/PokemonGo-Map#2646] opened 2016-07-29 19:09 UTC
## Expected Behavior
Continues to insert Pokemon each search if found.

## Current Behavior
Many searches are failing with the error "Search thread failed. Response dictionary key error"

Here is a snippet of code showing the frequency of it.

```
> 2016-07-29 19:09:06,379 [        models] [   INFO] Upserted 0 pokemon, 1 pokestops, and 1 gyms
> 2016-07-29 19:09:07,305 [        models] [   INFO] Upserted 0 pokemon, 1 pokestops, and 1 gyms
> 2016-07-29 19:09:07,333 [        models] [   INFO] Upserted 0 pokemon, 1 pokestops, and 1 gyms
> 2016-07-29 19:09:07,528 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:07,540 [        models] [   INFO] Upserted 0 pokemon, 4 pokestops, and 3 gyms
> 2016-07-29 19:09:07,674 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:07,816 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:07,970 [        models] [   INFO] Upserted 0 pokemon, 3 pokestops, and 3 gyms
> 2016-07-29 19:09:08,458 [        models] [   INFO] Upserted 0 pokemon, 3 pokestops, and 2 gyms
> 2016-07-29 19:09:08,471 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:08,617 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:08,678 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:08,773 [        models] [   INFO] Upserted 0 pokemon, 3 pokestops, and 2 gyms
> 2016-07-29 19:09:08,814 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:08,949 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:09,082 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:09,141 [        models] [   INFO] Upserted 1 pokemon, 22 pokestops, and 5 gyms
> 2016-07-29 19:09:09,228 [        search] [  ERROR] Search thread failed. Response dictionary key error
> 2016-07-29 19:09:09,230 [        search] [  ERROR] Niantic servers under heavy load. Waiting before trying again
```

## Steps to Reproduce (for bugs)
Simply running the program. Trying 4 threads which was normal in a previous update to my knowledge.

## Context
Fails to load many Pokemon, results in very few successful inserts.

## Your Environment
Running on Ubuntu 16.04 VPS

**Comment by miaojs** [comment] 2016-07-29 19:17
It's throttling.

**Comment by Paralysing** [comment] 2016-07-29 19:25
#2513

**Comment by ssbtoday** [comment] 2016-07-29 19:26
https://www.reddit.com/r/pokemongodev/comments/4v4akf/did_niantic_do_something_to_their_public_apis/

Throttling via Niantic. Close this issue, it's a duplicate of #2513

**Closed** 2016-07-29 19:40 UTC
