### ISSUE TITLE
Possible to Mark Captured Pokemons

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#1060] opened 2016-07-21 22:06 UTC
It would be great, and the new feature is when the user capture the pokemon have the option when click on it to mark as captured and the pokemon appear with one red X on it so the user will know that pokemon as been captured, and when the time expires it disappear, something like that would be cool

**Comment by DerScreever** [comment] 2016-07-21 22:15
really nice idea!

**Comment by medghaim** [comment] 2016-07-24 01:55
Duplicate of #1057. Closing.

SkyBadPT - Please don't open 2 issues for the same thing.

**Closed by medghaim** 2016-07-24 01:55 UTC
Labels: enhancement
