### ISSUE TITLE
Error on /gyms & /pokestops with 1818f9b6158b1375552b70d165170d4fba1a1d5f

### ISSUE THREAD

**Issue by therealshibe** [AHAAAAAAA/PokemonGo-Map#783] opened 2016-07-21 08:36 UTC
### Environment info
Operating System: 
win10

Installed version of Python:
Python 2.7.12 

### Steps to reproduce
1. pull 1818f9b6158b1375552b70d165170d4fba1a1d5f 
2. launch server
3. See output below

### What have you tried?
1. reverting to 1818f9b6158b1375552b70d165170d4fba1a1d5f for now fixes it. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
`
2016-07-21 01:32:25,516 [     models] [   INFO] Get Pokemons for stamp: 2016-07-21 01:32:14.499000
[2016-07-21 01:32:25,523] ERROR in app: Exception on /gyms [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\pogo\dev2\PokemonGo-Map\pogom\app.py", line 49, in gyms
    return jsonify([g for g in Gym.select().dicts()])
  File "C:\Python27\lib\site-packages\peewee.py", line 2047, in next
    obj = self.qrw.iterate()
  File "C:\Python27\lib\site-packages\peewee.py", line 2107, in iterate
    return self.process_row(row)
  File "C:\Python27\lib\site-packages\peewee.py", line 2196, in process_row
    res[column] = func(row[i])
  File "C:\Python27\lib\site-packages\peewee.py", line 1134, in python_value
    return format_date_time(value, self.formats)
  File "C:\Python27\lib\site-packages\peewee.py", line 180, in format_date_time
    return post_process(datetime.datetime.strptime(value, fmt))
AttributeError: 'module' object has no attribute '_strptime'
2016-07-21 01:32:25,526 [  _internal] [   INFO] 127.0.0.1 - - [21/Jul/2016 01:32:25] "GET /pokemons/1469089934499 HTTP/1.1" 200 -
2016-07-21 01:32:25,523 [        app] [  ERROR] Exception on /gyms [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\pogo\dev2\PokemonGo-Map\pogom\app.py", line 49, in gyms
    return jsonify([g for g in Gym.select().dicts()])
  File "C:\Python27\lib\site-packages\peewee.py", line 2047, in next
    obj = self.qrw.iterate()
  File "C:\Python27\lib\site-packages\peewee.py", line 2107, in iterate
    return self.process_row(row)
  File "C:\Python27\lib\site-packages\peewee.py", line 2196, in process_row
    res[column] = func(row[i])
  File "C:\Python27\lib\site-packages\peewee.py", line 1134, in python_value
    return format_date_time(value, self.formats)
  File "C:\Python27\lib\site-packages\peewee.py", line 180, in format_date_time
    return post_process(datetime.datetime.strptime(value, fmt))
AttributeError: 'module' object has no attribute '_strptime'
[2016-07-21 01:32:25,523] ERROR in app: Exception on /pokestops [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\pogo\dev2\PokemonGo-Map\pogom\app.py", line 45, in pokestops
    return jsonify(Pokestop.get())
  File "C:\Python27\lib\site-packages\flask\json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "C:\Python27\lib\site-packages\flask\json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python27\Lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Python27\Lib\json\encoder.py", line 442, in _iterencode
    o = _default(o)
  File "C:\pogo\dev2\PokemonGo-Map\pogom\app.py", line 80, in default
    return list(iterable)
TypeError: 'ResultIterator' object is not iterable
2016-07-21 01:32:25,563 [     search] [   INFO] Scanning step 8 of 225.
2016-07-21 01:32:25,523 [        app] [  ERROR] Exception on /pokestops [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\pogo\dev2\PokemonGo-Map\pogom\app.py", line 45, in pokestops
    return jsonify(Pokestop.get())
  File "C:\Python27\lib\site-packages\flask\json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "C:\Python27\lib\site-packages\flask\json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python27\Lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\Lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Python27\Lib\json\encoder.py", line 442, in _iterencode
    o = _default(o)
  File "C:\pogo\dev2\PokemonGo-Map\pogom\app.py", line 80, in default
    return list(iterable)
TypeError: 'ResultIterator' object is not iterable
`

**Comment by michi0987** [comment] 2016-07-21 08:36
Duplicate, fix underway https://github.com/AHAAAAAAA/PokemonGo-Map/issues/774

**Comment by MikeDX** [comment] 2016-07-21 08:37
duplicate of #774 ?

**Closed** 2016-07-21 08:37 UTC

**Comment by Zsub** [comment] 2016-07-21 08:38
Yup, dupe of #774 unfortunately. Still, great first issue @therealshibe! 

Probably fixed in #777 depending on whether they choose to merge that or another PR.
