### ISSUE TITLE
Cannot scanning pokemon,gym,pokestop

### ISSUE THREAD

**Issue by nurdiansyah01** [AHAAAAAAA/PokemonGo-Map#3437] opened 2016-08-04 02:25 UTC
How to fix this ?

2016-08-04 09:19:53,007 [     runserver] [   INFO] Parsed location is: 34.0108/-118.4958/0.0000 (lat/lng/alt)
2016-08-04 09:19:53,007 [        search] [   INFO] Search loop 0 starting
2016-08-04 09:19:53,007 [        search] [   INFO] Attempting login to Pokemon Go.
2016-08-04 09:19:53,007 [      auth_ptc] [   INFO] PTC login for: nurdiansyah
2016-08-04 09:19:58,158 [      auth_ptc] [   INFO] PTC Login successful
2016-08-04 09:19:59,190 [        search] [   INFO] Login to Pokemon Go successful.
2016-08-04 09:20:00,121 [        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-04 09:20:07,566 [        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-04 09:20:13,661 [        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

i enter in cmd : "C:\Python27\python.exe" runserver.py -a ptc -u username -p password -l "34.010808, -118.495793" -st 10 -k "API KEY"

thx b4 :)

**Comment by DarkAssassin011** [comment] 2016-08-04 02:27
You dont
[https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/](url)

**Comment by CorcoranEd** [comment] 2016-08-04 02:28
Same problem here. Login successful with google account, but no pokemon, pokestops, or gyms being upserted.

**Comment by TacticalPhallus** [comment] 2016-08-04 02:28
@DarkAssassin011 that link is not working, sending me to 404 Page not found

**Comment by clasherpekka** [comment] 2016-08-04 02:29
#3436

**Comment by dbendure** [comment] 2016-08-04 02:29
interesting it don't work on my end now too,

**Comment by DarkAssassin011** [comment] 2016-08-04 02:29
Weird, i just used it.

**Comment by TacticalPhallus** [comment] 2016-08-04 02:30
@DarkAssassin011  nvrmnd take out the "s" on https:

**Comment by DarkAssassin011** [comment] 2016-08-04 02:30
[http://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/](url) Still it works on https on my end

**Comment by nurdiansyah01** [comment] 2016-08-04 02:31
the link #404

**Comment by cdhowie** [comment] 2016-08-04 02:31
Duplicate of #3406

**Comment by nurdiansyah01** [comment] 2016-08-04 02:34
@cdhowie i will try it :)

**Closed** 2016-08-04 02:55 UTC
