### ISSUE TITLE
Getting Error on Startup

### ISSUE THREAD

**Issue by MinziMinzz** [AHAAAAAAA/PokemonGo-Map#3161] opened 2016-08-02 14:23 UTC
Everytime I try to start my Map, I get this Error.
The File "pokemon.min.json" does not exists, I tried to rename the File to "pokemon.json", but that does not work.

![startup](https://cloud.githubusercontent.com/assets/1565795/17331900/2e2b1358-58cd-11e6-8805-412694f94588.png)

**Comment by shiona** [comment] 2016-08-02 14:43
Duplicate of #2979

**Comment by MinziMinzz** [comment] 2016-08-02 14:45
Thanks mate

**Closed** 2016-08-02 14:45 UTC
