### ISSUE TITLE
Heroku unexpected server response

### ISSUE THREAD

**Issue by theebanka** [AHAAAAAAA/PokemonGo-Map#2788] opened 2016-07-31 03:58 UTC
I am sure I am missing something super easy and stupid but could someone help me resolve this issue or at least point me in a direction of what may be causing it? Each time I start the Heroku server and check the logs it goes through a cycle of:

`[      auth_ptc] [   INFO] PTC login for: Theebankamappa`
`[      auth_ptc] [   INFO] PTC Login successful`
`[       rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403`

Did I mess something up? Had a successfully version running before the  70m step change and went to update my version and now I am having this error... # #

**Comment by TorranceYang** [comment] 2016-07-31 04:20
Having this problem as well, created a new account and am still getting this error.

**Comment by pokefurydotcom** [comment] 2016-07-31 04:21
Same here.

**Comment by TorranceYang** [comment] 2016-07-31 04:24
I was hosting on azure, looks like niantic is blocking requests from certain blocks of ips: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2777

**Comment by marumari** [comment] 2016-07-31 04:40
Yep, this is just a dupe of #2777.

**Comment by DenisCarriere** [comment] 2016-07-31 04:47
Having the same issue using AWS EC2 instances.

**Comment by FrostTheFox** [comment] 2016-07-31 04:49
See reference above, Heroku blocked.

**Closed by FrostTheFox** 2016-07-31 04:49 UTC
Labels: duplicate
