### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by pavlukivan** [AHAAAAAAA/PokemonGo-Map#346] opened 2016-07-19 13:02 UTC
### Environment info
Operating System: Win7x64
Installed version of Python: 2.7.12

### Steps to reproduce
1. Run the program
2. ???
3. Profit!

### What have you tried?
1. Opening localhost:5000
Map is showing, but no pokemons there

### Logs or other output that would be helpful
```
C:\Python27\python.exe example.py -a google -u ???@gmail.com -p ??? -l "Tomsk" -st 5
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 611-552-907
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[!] Your given location: Tomsk, Tomsk Oblast, Russia
[!] lat/long/alt: 56.5010397 84.9924506 0.0
[!] Google login for: ???@gmail.com
[+] RPC Session Token: ??? ...
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
...
```

After a few of those messages it's going to next step, but once all steps are completed:
```
Completed: 100.0%
[-] register_background_thread called
[-] register_background_thread: queueing
[+] Locale is en
[-] looping: step 1 of 25
[+] Searching for Pokemon at location 56.5010397 84.9924506
```

**Comment by denniskai1234** [comment] 2016-07-19 13:03
Getting also tons of

[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

**Comment by mkody** [comment] 2016-07-19 13:12
Niantic servers are just dying, as always. Same issues than #344 and #345 

> See #342

**Comment by pavlukivan** [comment] 2016-07-19 13:50
I can play on my device, but the toool isn't working

**Comment by pavlukivan** [comment] 2016-07-19 14:05
And it's not the same as #342

**Comment by mkody** [comment] 2016-07-19 14:14
Even on my device it works, but it has got some lags and I'm quite a lot stuck on the animation where the Pokéball is twitching.
Pulling from the API still works. My loop of 25 can reach the end and fill the map, but it's just a bit slower to complete since it's _"retrying"_ a lot.

Also, same as https://github.com/AHAAAAAAA/PokemonGo-Map/issues/342#issuecomment-233622741 precisely, but a contributor closed it since it's looks like the problem is still from Niantic servers.
`¯\_(ツ)_/¯`

**Comment by pavlukivan** [comment] 2016-07-19 16:41
For me it's reaching the end also, but not filling the map, instead it's re-starting

**Closed** 2016-07-21 02:41 UTC
Labels: Not an issue: servers are down
