### ISSUE TITLE
Pokemon not showing on heroku

### ISSUE THREAD

**Issue by famendola1** [AHAAAAAAA/PokemonGo-Map#1071] opened 2016-07-21 22:47 UTC
I get this error in the heroku logs:

[  ERROR] Scan step failed. Response dictionary key error.

I don't know where the dictionary is being referenced

Also, at the end I get this: 

TypeError: unsupported operand type(s) for /: 'str' and 'int'

from the call:

remaining_time = api._auth_provider._ticket_expire/1000 - time.time()

**Comment by whippythought** [comment] 2016-07-21 23:48
Duplicate of #965 which was closed with no resolution.

**Comment by birdwell** [comment] 2016-07-22 04:25
I am getting the same error. The api._auth_provider._ticket_expire isn't an integer and you can't convert it to an int either. Might be tied to a certain version of python.

**Comment by macgngsta** [comment] 2016-07-22 05:55
Response dictionary key error was related to the pokemon go servers being down. iirc

**Comment by birdwell** [comment] 2016-07-22 12:30
The code should still fail gracefully and not stop everything.

**Comment by birdwell** [comment] 2016-07-22 12:39
Right now, I'm not getting it to go through another scan after the first one.

**Comment by c133** [comment] 2016-07-22 17:26
Getting the same unsupported operand type error on heroku instance. Is there a fix for this yet?

**Comment by medghaim** [comment] 2016-07-24 01:58
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Please direct support questions to: https://discordapp.com/invite/Kzp4yky

**Closed by medghaim** 2016-07-24 01:58 UTC
Labels: bug
