### ISSUE TITLE
Google with 2 step authentication

### ISSUE THREAD

**Issue by jcrrad** [AHAAAAAAA/PokemonGo-Map#583] opened 2016-07-20 16:39 UTC
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Any

Installed version of Python:
Any

### Steps to reproduce
1.Attempt to log in with any google account that has 2 step authentication enabled. 

### What have you tried?
1. python ./example.py -a google -u myUsername -l zipCode -st 10
2.  python ./example.py -a google -u myEmail-l zipCode -st 10
3. python ./example.py -a google -u myUsername@gmail.com -l zipCode -st 10

### Logs or other output that would be helpful
Exception wrong username/password

**Comment by rezz3x** [comment] 2016-07-20 16:40
Did you forget the -p arg, or just hided it?

**Comment by mkody** [comment] 2016-07-20 17:05
You should generate an application password and pass the generated password with the `-p` argument: https://security.google.com/settings/security/apppasswords

**Comment by Elyager** [comment] 2016-07-20 20:36
Hi @mkody I have generated the "token"  
![screenshot 2016-07-20 13 25 33](https://cloud.githubusercontent.com/assets/286888/17001880/bc2c0b9e-4e7d-11e6-860e-12142b9b2025.png)
which gives me a password like "xxx xxx xxx xxxx" so I'd tried with the following commands:
```bash
 ./runserver.py -a google -u elyager -p xxxxxxxxxxxx -l "New York" -st 100 -p 5000
 ./runserver.py -a google -u elyager -p "xxxx xxxx xxxx xxxx" -l "New York" -st 100 -p 5000
 ./runserver.py -a google -u "elyager@gmail.com" -p "xxxx xxxx xxxx xxxx" -l "New York" -st 100 -p 5000
```

![screenshot 2016-07-20 13 34 04](https://cloud.githubusercontent.com/assets/286888/17002157/e00a75fe-4e7e-11e6-8f3a-6798a42a073f.png)


but I still get the "Google Login failed" error, any help is appreciated 😁

**Comment by amussey** [comment] 2016-07-20 20:39
Hey @Elyager, you're second `-p` at the end needs to be a capital letter (`-P`).  Currently it's reading the password as `5000`.  :)

**Comment by CookieCookson** [comment] 2016-07-20 21:18
@Elyager you also have to remove the spaces from the password for it to work (the top of the three commands)

**Comment by Elyager** [comment] 2016-07-20 23:04
@CookieCookson  @amussey Thanks for your answers! is working now 👍

**Comment by DustinChaloupka** [comment] 2016-07-20 23:35
I'm not exactly sure how to go about PRing a wiki change (what I found by looking looked more complicated than necessary) but can a line like the following just be added to the wiki, possibly under the `FAQ` section when talking about Google authentication?

`If you happen to have 2-step verification enabled for your Google account you will need to supply an [app password](https://support.google.com/accounts/answer/185833?hl=en) for your password instead of your normal login password.`

**Comment by mayli** [comment] 2016-07-21 00:10
I am using app password, but why PokemonGo-Map trimming password?

[!] PTC login for: xxxxxxxxxx
[!] Trimming password to 15 characters
Your username or password is incorrect. You have 3 attempts left before you will be locked out of your account for 15 minutes.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 516, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password

**Comment by amussey** [comment] 2016-07-21 00:14
@mayli It looks like you're attempting to authenticate against the Pokemon Trainer Club instead of Google.  Do you have `-a google` as a parameter?

**Comment by mayli** [comment] 2016-07-21 00:16
@amussey `-a google` fixed the issue, thanks 👍

**Comment by mkody** [comment] 2016-07-21 09:11
So @jcrrad, is the issue resolved by what we've been discussing?
If so, or no responses, we can close this issue.

**Comment by jcrrad** [comment] 2016-07-21 12:09
I have not had a chance to test this out yet. but from what others are saying it seems like an App password will bypass any issue that is from 2 step auth.

**Comment by CookieCookson** [comment] 2016-07-21 12:22
I can confirm it works with an app password to skip 2 step auth.

**Comment by sykhro** [comment] 2016-07-21 22:23
Added to wiki, closing

**Closed by sykhro** 2016-07-21 22:23 UTC
Labels: enhancement
