### ISSUE TITLE
Wrong username/password

### ISSUE THREAD

**Issue by devian223** [AHAAAAAAA/PokemonGo-Map#19] opened 2016-07-17 18:27 UTC
I just tested your new code, but after some requests, I'm getting the following error:

[-] Wrong username/password

Before this you can see the entire HTML file that is send

My credentials are correct, this happens after it hits 15%

**Comment by me-12** [comment] 2016-07-17 18:35
True,. Having the same issue right now. Must have come with the latest commits. I haven't had this issue on marauder37's branch (https://github.com/marauder37/PokemonGo-Map) though.

**Comment by Dustinhoefer** [comment] 2016-07-17 18:44
Same for me =)

**Comment by devian223** [comment] 2016-07-17 18:44
Tried marauder37's branch, same problems

**Comment by AHAAAAAAA** [comment] 2016-07-17 18:54
Good catch, I noticed mine loads but after it's done loading it starts spamming wrong user/pass messages. I'll try to bug find.

**Comment by marauder37** [comment] 2016-07-17 18:56
I have some suggestions, that I can't do myself because the servers are down for me.

0. unless I miss my guess, the only way to exit the searching loop prior to 100% is to trigger the AttributeError in the middle of the main() loop. That's problem #1 to get to the bottom of, and design a classier solution than just `break`.
1. wrap login_ptc in a retry loop, the root cause of your "username or password error" could in fact be that the PTC servers get worse every hour
2. if there is a problem decoding the JSON inside login_ptc, tell us what was in r.content when it died
3. main() does about 3 jobs, it should be 3 functions. There is no reason to go through login every time we want to re-do the search.

**Comment by AHAAAAAAA** [comment] 2016-07-17 19:03
Servers intermittent here, it'll be easier in 5-6 hours when the peak is over. 

1. That's a good solution, ties in with #4 too. Most importantly we need to break up main to its specific functions so we can get a better grasp on error handling (especially with these servers).
2. I had a crass solution similar to this, but it was way too buggy. I'll look into a cleaner retry loop.
3. Yes.
4. Yes.

**Comment by robfrizzy** [comment] 2016-07-17 23:34
I'll just say that I too am having the same problem. Mine gets to 20% and step 2 of 10 and then starts throwing this error. Before it tells me I have a wrong username and password it states "could not decode JSON from"

**Comment by robfrizzy** [comment] 2016-07-18 03:42
Issue seems to be fixed in #45. Ran to 100% with no problems. Bug doesn't seem to be present in current master branch.

**Closed** 2016-07-18 04:00 UTC
Labels: bug
