### ISSUE TITLE
Question - Not seeing many pokemon.

### ISSUE THREAD

**Issue by craigbaines** [AHAAAAAAA/PokemonGo-Map#998] opened 2016-07-21 18:53 UTC
So im running the most recent dev build an it feels like im getting barley any pokemon show up compared to other builds i used before. 

Im running the following:

python runserver.py -a google -u "************" -p "*************" -l "Central Park, New York, NY" -st 10 -H 0.0.0.0 -P 7000

Heres what i mean:

![1](https://cloud.githubusercontent.com/assets/9383958/17034838/4d45c5da-4f7c-11e6-9b5b-dec6f27b2c53.jpg)

An for comparison the pokestops its finding:

![2](https://cloud.githubusercontent.com/assets/9383958/17034847/5ce6bbfc-4f7c-11e6-9dfc-8d9d249f78d0.jpg)

Iv'e tried playing with the 0.0025 from search.py:

"yield (x * 0.0025 + initial_location[0], y * 0.0025 + initial_location[1], 0)"

As iv'e seen people saying decreasing it, giving a bigger overlap may help, but thus far iv'e seen no difference :/

Correct me if im wrong but i was expecting (an did do earlier on) to see way more pokemon on the map here. 

Anything im doing wrong? / Not doing?

**Comment by Tigershark2005** [comment] 2016-07-21 18:55
Are you waiting for the full loop to run? -st 10 isn't a small space, of course not huge by comparision, but will take a while to loop through. Keep in mind that each loop of the script isn't an update but a new cell search. By the number of Pokestops you're showing over that area I'm guessing you have but I'm trying to start with that.

**Comment by craigbaines** [comment] 2016-07-21 18:58
Yeah iv'e had it running for ages, That definitely does seem far too few pokemon though right?

**Comment by tatarrr95** [comment] 2016-07-21 18:58
I have this problem too

**Comment by DerScreever** [comment] 2016-07-21 18:59
for me it scan a lot pokemon

**Comment by lexa19800806** [comment] 2016-07-21 19:00
класс!!!!

**Comment by craigbaines** [comment] 2016-07-21 19:00
Here's an image from i think, the master branch, or at least an earlier dev one. Seems like a big difference to me. I have no idea why though, i think im doing everything the same way. 

![3](https://cloud.githubusercontent.com/assets/9383958/17035151/c7f9bb3c-4f7d-11e6-82fd-8e9c6dc188e5.png)

**Comment by DeastinY** [comment] 2016-07-21 19:02
Could this be because Pokemon attracted by lure are not shown ?

**Comment by Tigershark2005** [comment] 2016-07-21 19:27
I'd say that's possible, all pokemon that this script hears about are returned from the server. I'd say there's a good chance that organic spawns are returned but lure/incense are specific to that user. In the case of lures, that small area....but still targeting the user and not the map as a whole.

**Comment by downwithbgp** [comment] 2016-07-21 19:54
I confirm no visibility into Pokemon spawned by lure modules.

**Comment by ApocUSB190** [comment] 2016-07-21 20:02
I can also confirm that I do not see any pokemon near lured pokestops.

![pgo2](https://cloud.githubusercontent.com/assets/6667498/17036929/0bf26a16-4f54-11e6-8fe6-2623fbe9f536.PNG)

**Comment by DeastinY** [comment] 2016-07-21 20:20
I'd believe it's rather intentional. Lurespawn are gone rather quickly and would just pollute the map and get your hopes up :D

**Comment by craigbaines** [comment] 2016-07-21 20:47
But would they not still spawn near lured pokestops as normal ones?

**Comment by DeastinY** [comment] 2016-07-21 20:57
If I understand correctly you're asking whether Pokemon casually spawning near lures, but not spawned by lures, are shown.
That's the question, then my answer is: They should be shown.
From what I've seen so far there is a difference between pokemon "attracted" (aka spawned) by lure, and casual spawns. Those casual spawns are shown and should not be affected by the lure.

**Comment by sojor** [comment] 2016-07-21 21:08
I can reproduce the same issue as OP. Master branch constantly shows more Pokemon than develop branch indepentent of items or expiration. Develop branch simply doesn't show several Pokemon even if they have 10+ minutes on the clock.

**Comment by Sejadis** [comment] 2016-07-21 21:15
could be (hopefully is) fixed with #776

**Comment by sojor** [comment] 2016-07-21 22:06
I tryed #776 search.py. With standard settings the search results were still inferior to the master branch. With m=200 tho (was 240) it seems to work better.

**Comment by FoxxMD** [comment] 2016-07-22 00:48
This doesn't have anything to do with lures. Can also confirm it favors the upper quadrant.

## master branch

![screen shot 2016-07-21 at 8 46 26 pm](https://cloud.githubusercontent.com/assets/4663766/17043412/644a626a-4f84-11e6-873b-f45c9e7b4ca3.png)

## develop branch

![screen shot 2016-07-21 at 8 46 15 pm](https://cloud.githubusercontent.com/assets/4663766/17043420/783c67fa-4f84-11e6-93dd-a883ea4181e1.png)

**Comment by Tigershark2005** [comment] 2016-07-22 01:59
I'm definitely not using the develop branch until the amount is at or better than master.

**Comment by Tigershark2005** [comment] 2016-07-22 01:59
I'll also say the upper portion is 1 for 1. So it must break down during the loop.

**Comment by craigbaines** [comment] 2016-07-22 11:01
This morning ( running the latest) im getting way more pokemon, but i guess my loop is way too slow, the middle all expire while its finding them int he outer areas and likewise the outer expires while its in the middle. 

I don't know if changes were made or this is all just utterly random, I'm just scatching my head wondering whats going on mostly lol

![4](https://cloud.githubusercontent.com/assets/9383958/17055338/0a8413c2-5004-11e6-88db-2cfb7f5b7a37.png)

**Comment by craigbaines** [comment] 2016-07-22 19:31
So i asked a question #1319 to do with multiple instances, one thing i read to get rid of the error i was getting is to basically ditch pokestops. 

Doing that instantly gave me a way faster search loop and so so so many more pokemon. I think because of central park having so many pokestops its some how bogging it down? 

Just look at the differance after a few mins running,plus i have two instances going hence two areas of pokemon.

![new](https://cloud.githubusercontent.com/assets/9383958/17068854/3e1d5742-504b-11e6-8de0-3e4236519f16.png)

**Comment by ProtoxiDe22** [comment] 2016-07-22 19:55
So all this could be due to a database limitation? i will test asap (at this time PTS servers seem down) however in my area there aren't as much pokestops and pokemons as central park. if i were able do display the same number of object you have in the screenshot it wouldn't be a problem for me.

**Comment by craigbaines** [comment] 2016-07-22 19:57
Just switch them to central park? lol

**Comment by ProtoxiDe22** [comment] 2016-07-22 19:58
i could try, but the problem's still there and at this point i think we have no clue of what's happening

**Comment by craigbaines** [comment] 2016-07-22 20:01
I just used @TheReaperr fix by commenting in models.py:

#if pokestops:
# log.info("Upserting {} pokestops".format(len(pokestops)))
# bulk_upsert(Pokestop, pokestops)

taking that out has made everything run perfect for me. Im seeing 1000% more pokemon, my search loop is running is a 10th of the time.

I really do think in my case at least, the large number of pokestops is a big problem, an im pretty sure that the way it is now even when i hide the pokestops on the UI there still getting searched for or whatever in the code unlike earlier editions...

**Comment by TheReaperr** [comment] 2016-07-22 23:25
@craigbaines  yeah the data is still collected and upserted to the database, whether u show/hide pokestop on the map it doesn't matter.

**Comment by medghaim** [comment] 2016-07-24 01:47
This is a known issue that is being addressed. Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky

**Closed by medghaim** 2016-07-24 01:47 UTC
Labels: bug
