### ISSUE TITLE
Long run time results in blank map

### ISSUE THREAD

**Issue by ericpadilla** [AHAAAAAAA/PokemonGo-Map#457] opened 2016-07-20 01:43 UTC
Hi, after running the program for more than an hour, the pokemon does not re-appear on the map at all, therefore the map became empty. Is there any fix to this? Thanks!

The steps kept on loading with no problem such as api error and stuffs.

**Comment by hgentry** [comment] 2016-07-20 01:49
I've noticed this, too. I think it's because a broken pipe error occurs at some point and we don't notice it. I've seen it once or twice, but didn't connect it to the blank map. If I see it again I'll grab the error.

**Comment by pskitz** [comment] 2016-07-20 01:50
I had this happen as well. I just restarted the script and it fixed the issue. I didn't notice anything off about the console though, just that there were no pokemon on the map.

**Comment by Skullmonkey** [comment] 2016-07-20 02:14
Same here. Happens after about 30ish mins of running.

**Comment by ericpadilla** [comment] 2016-07-20 02:19
But i could not restart the script when i'm outside. 1 hour drive from home to university. I couldn't find the error, everything running out fine in the cmd.

**Comment by talentedmrripley** [comment] 2016-07-20 03:21
@ericpadilla I'm running a scheduled task to kill the process once an hour, about the longest it seems stable for me, and then restarting it.  Until there's a fix you'll probably need a workaround.  You could also setup some kind of remote access to the machine running it, a la TeamViewer, so that you can restart it that way.

**Comment by foodforarabbit** [comment] 2016-07-20 03:22
hey guys this should fix it: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/465

I've been running it for 30 minutes and it seems to be fine so far

**Comment by ericpadilla** [comment] 2016-07-20 04:40
im testing it, will close after 2 hours of testing. Thanks for the fix though!

**Comment by ericpadilla** [comment] 2016-07-20 04:52
@foodforarabbit the map became empty after ~48 minutes of running non-stop.

**Comment by vDrag0n** [comment] 2016-07-20 04:59
Tested fix,  Same problem here also, map disappears after 30mins.

**Comment by ericpadilla** [comment] 2016-07-20 05:23
For now, Im jusing teamviewer on ios to control my pc remotely and restart script manually. seems to work for me!

**Comment by sandsaber** [comment] 2016-07-20 07:32
Not fixed. Can confirm clean map after ~40 min of running. 
![pok2](https://cloud.githubusercontent.com/assets/951406/16978580/3b1c4018-4e65-11e6-8f31-1c51b26ccf43.png)

**Comment by sandsaber** [comment] 2016-07-20 07:33
Probably same as https://github.com/AHAAAAAAA/PokemonGo-Map/issues/325

**Comment by nikos90** [comment] 2016-07-20 08:17
The problem is not in the pins.
`for hh in hs:
        try:
            for cell in hh.cells:
                for wild in cell.WildPokemon:`

no cell after some time.
checking now the heartbeat response

**Comment by nikos90** [comment] 2016-07-20 08:46
Confirm.
The heartbeat return 'None' after some time.

**Comment by Tzeentchful** [comment] 2016-07-20 09:21
I believe this is a result of the access token becoming expired. There is an expiry field on the SSO return that would suggest that this is the case.
`access_token=TGT-******-**************************-sso.pokemon.com&expires=7198`
Should be fixed by just need to get a new token every now and again

**Comment by nikos90** [comment] 2016-07-20 09:22
Very possible @Tzeentchful

**Comment by nikos90** [comment] 2016-07-20 09:59
`
def process_step(args, api_endpoint, access_token, profile_response,
                 pokemonsJSON, ignore, only):
    print('[+] Searching pokemons for location {} {}'.format(FLOAT_LAT, FLOAT_LONG))
    origin = LatLng.from_degrees(FLOAT_LAT, FLOAT_LONG)
    step_lat = FLOAT_LAT
    step_long = FLOAT_LONG
    parent = CellId.from_lat_lng(LatLng.from_degrees(FLOAT_LAT,
                                                     FLOAT_LONG)).parent(15)
    h = get_heartbeat(args.auth_service, api_endpoint, access_token,
                      profile_response)
    
    if h is None:
        args = get_args()
        profile_response = login(args)
`

actually testing this ..

**Comment by DerScreever** [comment] 2016-07-20 11:31
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team

**Closed by DerScreever** 2016-07-20 11:31 UTC
Labels: bug
