### ISSUE TITLE
Wont't show any pokemon

### ISSUE THREAD

**Issue by Koen-K** [AHAAAAAAA/PokemonGo-Map#3463] opened 2016-08-04 14:14 UTC
Is does scan and the pokestops and gyms are showing, but no pokemon. Anyone else with the same problem? I tried making new PTC accounts.

**Comment by Reubenwelsh** [comment] 2016-08-04 14:17
do a search next time

**Comment by Koen-K** [comment] 2016-08-04 14:18
What do you mean, I got the 16 searchers

**Comment by DANDWYERIRL** [comment] 2016-08-04 14:20
It is due to an API change. There is a notice in the wiki posted today

**Comment by cdhowie** [comment] 2016-08-04 14:22
Duplicate of #3406

**Comment by aldarund** [comment] 2016-08-04 14:23
Use  a f**g search before posting another duplicate. And read at least main of repo and open your eyes

**Comment by licklake** [comment] 2016-08-04 14:26
#closerequest

**Comment by reikix** [comment] 2016-08-04 14:26
Seriously, f***ing read before whining here.

**Closed** 2016-08-04 14:36 UTC
