### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by Xerocry** [AHAAAAAAA/PokemonGo-Map#942] opened 2016-07-21 16:49 UTC
Trying to run map, get:

`SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

**Comment by fettlaus** [comment] 2016-07-21 16:50
Duplicate of #821 ?

**Comment by Xerocry** [comment] 2016-07-21 16:53
No, another log. 

`Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
File "C:\Python27\lib\threading.py", line 754, in run
 self.__target(*self.__args, **self.__kwargs)
File "C:\Users\raskia\Documents\PokemonGo-Map-develop\pogom\search.py", line 9
4, in search_loop
    search(args)
  File "C:\Users\raskia\Documents\PokemonGo-Map-develop\pogom\search.py", line 6
9, in search
    login(args, position)
 File "C:\Users\raskia\Documents\PokemonGo-Map-develop\pogom\search.py", line 5
0, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "C:\Users\raskia\Documents\PokemonGo-Map-develop\pogom\pgoapi\pgoapi.py",
 line 144, in login
    if not self._auth_provider.login(username, password):
  File "C:\Users\raskia\Documents\PokemonGo-Map-develop\pogom\pgoapi\auth_ptc.py
", line 52, in login
    r = self._session.get(self.PTC_LOGIN_URL, headers=head)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request    
resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

**Closed** 2016-07-21 22:12 UTC
Labels: bug
