### ISSUE TITLE
Pokemon Icons disappear after ~5 secs

### ISSUE THREAD

**Issue by 5andr0** [AHAAAAAAA/PokemonGo-Map#761] opened 2016-07-21 06:32 UTC
For the past 5 hours my pokemon icons are disappearing shortly after a refresh. F5 however makes them reappear for 5 seconds again. This happens with -ar on/off and on every browser i got. I'm on the develop branch and tried to redownload aswell.

I also get lots of these errors in multiple files:
    return post_process(datetime.datetime.strptime(value, fmt))
AttributeError: 'module' object has no attribute '_strptime'

**Comment by fust** [comment] 2016-07-21 06:35
Can confirm the disappearing of icons happens here too.
I don't get the errors in the console though, seems to be an unrelated issue.

**Comment by daruda87** [comment] 2016-07-21 06:40
same here with disappearing pokémon icons.
Need to refresh to get them back and will disappear again after 5s

**Comment by shadow7412** [comment] 2016-07-21 06:47
Duplicate of https://github.com/AHAAAAAAA/PokemonGo-Map/issues/741

**Closed** 2016-07-21 07:02 UTC
Labels: bug, duplicate
