### ISSUE TITLE
"No google maps Javascript API enetered"

### ISSUE THREAD

**Issue by PhinniX** [AHAAAAAAA/PokemonGo-Map#2310] opened 2016-07-27 11:21 UTC
Hey, when i run the thing with "python runserver.py -a ptc -u ****** -p ****** -l "Some Location" -st 10" it says, 

C:\Users\gardedue\Desktop\PokemonGo-Map-master>C:\Python27\python runserver.py -a ptc -u ******* -p ******* -l "Union Square, San Francisco" -st 10
2016-07-27 13:19:07,746 [  runserver] [   INFO] Parsed location is: 37.7880/-122.4074/0.0000 (lat/lng/alt)
2016-07-27 13:19:07,755 [     search] [   INFO] Map iteration: 0
2016-07-27 13:19:07,757 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-27 13:19:07,763 [   auth_ptc] [   INFO] PTC login for: ******
Traceback (most recent call last):
  File "runserver.py", line 76, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "C:\Users\******\Desktop\PokemonGo-Map-master\pogom\utils.py", line 142, in load_credentials
    "No Google Maps Javascript API key entered in \config\credentials.json file!"
pogom.exceptions.APIKeyException: No Google Maps Javascript API key entered in \config\credentials.json file! Please take a look at the wiki for instructions on how to generate this key, then add that key to the file!
Exception in thread search_thread (most likely raised during interpreter shutdown):
C:\Users\*****\Desktop\PokemonGo-Map-master>

so it doenst work.. anyone got an idea on how to fix this for me?

**Comment by emsyzz** [comment] 2016-07-27 11:28
Have you tried entering gmaps_key in config\credentials.json?

**Comment by PhinniX** [comment] 2016-07-27 11:29
I just did, it says gmaps_key is not recognized

**Comment by emsyzz** [comment] 2016-07-27 11:31
What versionare you using?

**Comment by PhinniX** [comment] 2016-07-27 11:31
2.7

**Comment by emsyzz** [comment] 2016-07-27 11:32
No, version of PokemonGo-Map

**Comment by PhinniX** [comment] 2016-07-27 11:34
uhhhh how do i see that?
i can tlel you i downloaded it yesterday

**Comment by PhinniX** [comment] 2016-07-27 12:00
ehh???

**Comment by Jorgixhallo** [comment] 2016-07-27 12:17
You need to input your own google map key in \config\credentials.json, not "gmaps_key". Check the wiki as stated in the error message.

You can use https://discord.gg/dfnG2 for more help.

@medghaim you can close this now I think :)

**Comment by Akabane87** [comment] 2016-07-27 12:54
Actually you need to also enable the different API used by the server in the API manager (otherwise you get a client error telling you the API key is not valid for this API). I had to enable :
- Google Maps JavaScript API
- Google Maps Embed API
- Google Maps Geolocation API

**Comment by PhinniX** [comment] 2016-07-27 13:37
Jorgixhallo, i dont get it "check the wiki" which wiki and were? im new to this site

**Comment by PhinniX** [comment] 2016-07-27 13:38
Akabane87, how do i enable those API things??

**Comment by tarthim** [comment] 2016-07-27 13:39
Wiki: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki
Google Map API guide specific: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by robertpro** [comment] 2016-07-27 16:03
I had the same issue, but i tried witu config/config.ini, and it works! :D

**Comment by PhinniX** [comment] 2016-07-27 19:57
Robertpro, where do i type config/config.ini 
and whats -se option?

**Comment by PhinniX** [comment] 2016-07-27 19:58
2016-07-27 21:58:23,822 [   auth_ptc] [   INFO] PTC login for: PhinniX020202
2016-07-27 21:58:24,483 [   auth_ptc] [  ERROR] Could not retrieve token: As a security measure, your account has been disabled for 15 minutes because you have failed to log in correctly too many times. Please come back and try again in 15 minutes.
2016-07-27 21:58:24,487 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.
2016-07-27 21:58:25,492 [   auth_ptc] [   INFO] PTC login for: PhinniX020202
2016-07-27 21:58:26,157 [   auth_ptc] [  ERROR] Could not retrieve token: As a security measure, your account has been disabled for 15 minutes because you have failed to log in correctly too many times. Please come back and try again in 15 minutes.
2016-07-27 21:58:31,105 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.

**Comment by PhinniX** [comment] 2016-07-27 19:58
this pops up now

**Comment by robertpro** [comment] 2016-07-27 21:13
@PhinniX ok, lets do this.. I supposed that you are using a *NIX system like Linux, and you have cloned the repo (git clone https://github.com/AHAAAAAAA/PokemonGo-Map)

First, you have to get the latest stable version:
`git clone https://github.com/AHAAAAAAA/PokemonGo-Map`
`cd PokemonGo-Map `
`ls config/config.ini `
> Add your settings to this file (auth-service, username, password, location, Google_Maps_API_Key)

Then run the following command, it should be running correctly:
`python runserver.py -se`

**Comment by chuyskywalker** [comment] 2016-07-30 06:04
Feel free to continue seeking help, but as this is not a bug/feature thread, I'm going to close it.

**Closed by chuyskywalker** 2016-07-30 06:04 UTC
