### ISSUE TITLE
Map doesnt show all pokemons around

### ISSUE THREAD

**Issue by aviel600** [AHAAAAAAA/PokemonGo-Map#819] opened 2016-07-21 10:43 UTC
### Environment info
Operating System: Win 7 64 bit

Installed version of Python: 2.7

HI, it seems like the map doesnt show a lot of pokemon in my area, only 30-40%
when I enter the game in the exact location i see a lot of pokemons that doesnt appear in the map
I use the develop branch, 
the command i use each time is as it says in the wiki:
python runserver.py -a ptc -u [USERNAME] -p [PASSWORD] -l "Location" -st 10

is it supposed to be like that ?

**Comment by cschmatzler** [comment] 2016-07-21 10:45
Possible dupe of #741?
Try the fix that is mentioned there and check if it's the same issue as yours.

**Comment by medghaim** [comment] 2016-07-21 10:49
#755 

This is known, and being looked into.

**Closed by medghaim** 2016-07-21 10:49 UTC
Labels: duplicate

**Comment by aviel600** [comment] 2016-07-21 12:35
Hi, thanks for the support.
These changes were already built in when i downloaded the develop branch so actually i had nothing to update except for the req_sleep... i changed it to 2 as it sais there but still nothing changed and still there are much less pokemons in the map than it supposed to be.

**Comment by aviel600** [comment] 2016-07-21 12:39
@medghaim
