### ISSUE TITLE
protobuf containers.py:64 IndexError: list index out of range 

### ISSUE THREAD

**Issue by HenrySia** [AHAAAAAAA/PokemonGo-Map#261] opened 2016-07-19 05:34 UTC
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 14.04
Installed version of Python:
2.7.11

### Steps to reproduce
1. python example.py -u "Username" -p "Password" -l "Seattle, WA" -st 10 -H "0.0.0.0" -P 9000 -i "zubat,weedle,caterpie,spearow,pidgey,drowzee,krabby,paras,rattata" -ar 15
2. Let it run for a while

### What have you tried?
1. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

> [+] Searching pokemons for location 47.7581531 -122.3440178}
> Exception in thread search_thread:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 1073, in run
>     self.function(*self.args, **self.kwargs)
>   File "example.py", line 599, in main
>     pokemonsJSON, ignore, only)
>   File "example.py", line 626, in process_step
>     profile_response)
>   File "example.py", line 416, in get_heartbeat
>     payload = response.payload[0]
>   File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/containers.py", line 64, in getitem__
>     return self._values[key]
> IndexError: list index out of range

**Comment by Octylpy** [comment] 2016-07-19 05:35
Duplicate of #254

**Comment by DerScreever** [comment] 2016-07-19 05:35
#257

**Closed** 2016-07-19 05:35 UTC
