### ISSUE TITLE
Please, migrate from Google-Maps to OpenStreetMap

### ISSUE THREAD

**Issue by theg4sh** [AHAAAAAAA/PokemonGo-Map#1705] opened 2016-07-24 00:55 UTC
Well, it's a little problem to get a key for any users, who want to use this map locally.
So, could you, please, add support for OSM map rendering?
Examples showed here http://leafletjs.com/examples.html gives the same functionality.

**Comment by matslarson** [comment] 2016-07-24 00:58
Not to sound like a dick, but how is getting your own API key difficult?

**Comment by callmebackdraft** [comment] 2016-07-24 01:01
Seeing as the entire code is based on gmaps i dont think this will happen, aside from that every user willing to install this can request a gmapskey withou issue to my knowledge

**Comment by BillyWM** [comment] 2016-07-24 01:18
Duplicate of https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1589. There's some discussion over there.

**Comment by MonkeyLeeT** [comment] 2016-07-24 01:39
We'd welcome anyone send in another map.html using different map. Just not what we'll focus now.

At least I know some people are working on migration, hopefully they'll PR something.

**Closed by MonkeyLeeT** 2016-07-24 01:39 UTC
