### ISSUE TITLE
Previous PokeMap version shows more pokemons, why?

### ISSUE THREAD

**Issue by zenwalk92** [AHAAAAAAA/PokemonGo-Map#1866] opened 2016-07-24 18:18 UTC
Previous PokeMap version shows more pokemons, why? An the second thing. Ver 1 and ver 2 showing different pokemons in the same time

**Comment by Sp0one** [comment] 2016-07-24 18:27
I notice the same regression. With a version of 21/07 (22:00) the number of pokemon shown on the map is higher than with the latest version. Is it a bug? It's like the scanner has less accuracy or something.

**Comment by Chlodochar** [comment] 2016-07-24 18:31
This should be solved by using `-t 1`. It had something to do with multiple threads accessing the same SQLite database.

**Comment by Chlodochar** [comment] 2016-07-24 18:32
Duplicate of https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1540

**Closed by Chlodochar** 2016-07-24 18:32 UTC

**Comment by Sp0one** [comment] 2016-07-24 18:36
Thank you ! The solution worked for me.
