### ISSUE TITLE
After 30 minutes it fails to login..

### ISSUE THREAD

**Issue by Playfrog4u** [AHAAAAAAA/PokemonGo-Map#1142] opened 2016-07-22 06:35 UTC
Runs for about 30 minutes or so and then logs out and won't log back in. I have to manually restart it.
This is the log when it fails to login.
```
2016-07-22 01:24:52,859 [   auth_ptc] [   INFO] PTC Login successful
2016-07-22 01:24:53,000 [     pgoapi] [  ERROR] Login failed - unexpected server response!
2016-07-22 01:24:53,001 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.
```

**Comment by seraphbreak** [comment] 2016-07-22 06:41
I just had the same issue occur on 2 different machines.

**Comment by benemorius** [comment] 2016-07-22 06:47
Which commit please? And can you try to capture the very first login failure along with a few dozen preceding lines?

**Comment by Playfrog4u** [comment] 2016-07-22 06:49
Based off the dev branch. And other changes to allow more features. I will see if I can catch it.

**Comment by seraphbreak** [comment] 2016-07-22 06:55
Mine occurred after a scan completed, see below. -sd set to 30

> 2016-07-21 23:36:42,902 [     models] [   INFO] Upserting 3 pokestops
2016-07-21 23:36:42,906 [     models] [   INFO] Upserting 2 gyms
2016-07-21 23:36:42,908 [     search] [   INFO] Completed 100.00% of scan.
2016-07-21 23:36:43,915 [     search] [   INFO] Scanning complete.
2016-07-21 23:36:43,916 [     search] [   INFO] Waiting 30 seconds before beginning new scan.
2016-07-21 23:36:47,394 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:36:47] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:36:51,573 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:36:51] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:36:56,577 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:36:56] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:37:01,576 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:37:01] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:37:08,519 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:37:08] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:37:12,500 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:37:12] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:37:13,925 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 23:37:13,933 [   auth_ptc] [   INFO] PTC login for: USERNAME
2016-07-21 23:37:17,059 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:37:17] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:37:23,429 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:37:23] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:37:25,549 [   auth_ptc] [   INFO] PTC Login successful
2016-07-21 23:37:25,837 [     pgoapi] [  ERROR] Login failed - unexpected server response!
2016-07-21 23:37:25,837 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.
2016-07-21 23:37:26,854 [   auth_ptc] [   INFO] PTC login for: USERNAME
2016-07-21 23:37:26,869 [  _internal] [   INFO] 192.168.1.2 - - [21/Jul/2016 23:37:26] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-21 23:37:27,627 [   auth_ptc] [   INFO] PTC Login successful
2016-07-21 23:37:27,866 [     pgoapi] [  ERROR] Login failed - unexpected server response!
2016-07-21 23:37:27,866 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.

**Comment by Playfrog4u** [comment] 2016-07-22 06:57
Same for me

**Comment by Playfrog4u** [comment] 2016-07-22 07:05
```
2016-07-22 02:02:26,591 [     search] [   INFO] Scanning step 400 of 400.
2016-07-22 02:02:26,662 [     search] [   INFO] Completed 100.00% of scan.
2016-07-22 02:02:27,205 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:27] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 200 -
2016-07-22 02:02:27,292 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:27] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 200 -
2016-07-22 02:02:27,663 [     search] [   INFO] Scanning complete.
2016-07-22 02:02:28,650 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:28] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-22 02:02:28,660 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:28] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-22 02:02:28,664 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-22 02:02:28,665 [   auth_ptc] [   INFO] PTC login for: USERNAME
2016-07-22 02:02:28,729 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:28] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-22 02:02:29,281 [   auth_ptc] [   INFO] PTC Login successful
2016-07-22 02:02:29,376 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:29] "GET /static/icons/72.png HTTP/1.1" 200 -
2016-07-22 02:02:29,461 [     pgoapi] [  ERROR] Login failed - unexpected server response!
2016-07-22 02:02:29,461 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.
2016-07-22 02:02:29,815 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:29] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 200 -
2016-07-22 02:02:29,907 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:29] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 200 -
2016-07-22 02:02:30,463 [   auth_ptc] [   INFO] PTC login for: USERNAME
2016-07-22 02:02:31,159 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:31] "GET /raw_data?pokemon=true&pokestops=false&gyms=true HTTP/1.1" 200 -
2016-07-22 02:02:31,469 [   auth_ptc] [   INFO] PTC Login successful
2016-07-22 02:02:31,475 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:31] "GET /raw_data?pokemon=true&pokestops=false&gyms=false HTTP/1.1" 200 -
2016-07-22 02:02:31,647 [     pgoapi] [  ERROR] Login failed - unexpected server response!
2016-07-22 02:02:31,647 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.
2016-07-22 02:02:32,211 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:32] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 200 -
2016-07-22 02:02:32,293 [  _internal] [   INFO] 10.0.0.1 - - [22/Jul/2016 02:02:32] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 200 -
2016-07-22 02:02:32,649 [   auth_ptc] [   INFO] PTC login for: USERNAME
```

**Comment by benemorius** [comment] 2016-07-22 07:27
Does it correct itself within a few minutes if you leave it running?

**Comment by noaqzz** [comment] 2016-07-22 07:29
Confirmed, not refreshing

**Comment by seraphbreak** [comment] 2016-07-22 07:31
I actually had one that fixed itself after 7 tries, but I've seen it fail continuously like 30x times before I re-ran the command and it worked fine.

**Comment by matpag** [comment] 2016-07-22 07:40
Same problem for me

**Comment by brumie** [comment] 2016-07-22 08:56
problem with pogo server, please check status on https://go.jooas.com/
up & down for an hour

**Comment by devian223** [comment] 2016-07-22 08:56
Same here, have noticed this for a long time. I don't this it has something to do with the server, because it also occurs when servers are continuously up, it stops at exactly 30 minutes. I think the issue is in pokemon_pb2.py

**Comment by carmenchui** [comment] 2016-07-22 15:57
same for me right now... can't authenticate to either google or ptc

**Comment by MonkeyLeeT** [comment] 2016-07-24 02:23
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

**Closed by MonkeyLeeT** 2016-07-24 02:23 UTC
