### ISSUE TITLE
Multiple notifications for same Pokemon

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#1951] opened 2016-07-25 07:06 UTC
Using the 'Notify of Pokemon', I get sent a notification everytime I:

* refresh
* click on notification
* blink
* apologize
* random

Expected behaviour:
One notification per pokemon

**Comment by ericpadilla** [comment] 2016-07-25 07:07
I confirmed this is true.

**Comment by nallsnowblind** [comment] 2016-07-25 07:58
Confirm
It happens when the map reloads
Same is when you zoom in and out again. The pokemon will then be redrawn on the map and notification is sent again.

**Comment by p4pergoat** [comment] 2016-07-25 08:01
Yeah, this is true. It also spams you with notifications when the pokemon you wanted to get notified for despawns (gets removed from the map).

**Comment by rjwestman** [comment] 2016-07-25 10:18
it also happens everytime the scanner finds the pokemon - so 3 times for each pokemon (since it uses a triangulation to find its exact location, right?
So basically the notification trigger needs to be moved to where the pokemon is added to the map. Would also be nice to give it a glow of some kind to find it more easily (when scanning a large area)

**Comment by AHAAAAAAA** [comment] 2016-07-25 14:56
@rjwestman It doesn't use triangulation.

**Comment by DerScreever** [comment] 2016-07-25 18:46
should be fixed with #2017

**Comment by parkershepherd** [comment] 2016-07-26 01:03
@DerScreever the fix I made should only apply when you zoom in/out but the pokemon remains in the view the whole time. If you zoom out to a new area or pan to a new area, you will still get notified about pokemon that you could have already been notified about before (although maybe that's the best behavior?)

**Comment by parkershepherd** [comment] 2016-07-26 01:06
those notifications are a side effect of `clearOutOfBoundsMarkers`, which does speed up the map hugely if you have a large scan area

**Comment by invisiblek** [comment] 2016-07-26 14:54
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2206

**Comment by invisiblek** [comment] 2016-07-26 14:55
ah shit, that didn't work as expected

**Comment by invisiblek** [comment] 2016-07-26 15:30
not the prettiest thing in the world: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2214

**Comment by PiaFraus** [comment] 2016-07-26 16:49
I think it's fixed in #2131

**Comment by invisiblek** [comment] 2016-07-27 15:55
ended up being fixed with: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2282

**Closed by invisiblek** 2016-07-27 15:55 UTC
Labels: bug
