### ISSUE TITLE
Scrolling on the filter page

### ISSUE THREAD

**Issue by commanderjsoc** [AHAAAAAAA/PokemonGo-Map#2101] opened 2016-07-25 22:50 UTC
## Expected Behavior

When there are too many pokemon in the notify and exclude areas, the column should have a scroll bar to see the rest of the pokemon

## Current Behavior

Right now the only way to see the rest of the pokemon is to adjust the zoom of the browser

## Possible Solution

Add a scroll bar? that might work...

## Steps to Reproduce (for bugs)

1. open the pogomap(localhost:5000)
2. Add a bunch of pokemon to the exclude/notify areas
3. Watch in agony as you cant add any more
4.

## Context

I would like to be able to see all of those listed pokemon

## Your Environment

* Version used: lastest dev branch
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): desktop MacOS Sierra, Firefox

**Comment by callmebackdraft** [comment] 2016-07-25 23:22
duplicate of: #2085 please use search function before posting an issue
and Pull Request:#2106  posted to fix this

**Closed** 2016-07-28 16:15 UTC
