### ISSUE TITLE
"Map Download failed. Trying again." on develop branch 

### ISSUE THREAD

**Issue by FaizSayyid** [AHAAAAAAA/PokemonGo-Map#649] opened 2016-07-20 20:29 UTC
Running the new develop branch, i get these a lot of the time:

[    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
[     search] [   INFO] Map Download failed. Trying again.

Is this a bug or a server side issue?

**Comment by jonathan-dejong** [comment] 2016-07-20 20:30
Same here :) Posting to follow!

**Comment by Rebosar** [comment] 2016-07-20 20:30
Also getting the same error. I believe it is a server issue.

**Comment by mkody** [comment] 2016-07-20 20:32
Servers are down. [Duplicate of many other issues.](https://github.com/AHAAAAAAA/PokemonGo-Map/labels/Not%20an%20issue%3A%20servers%20are%20down)

**Comment by MonkeyLeeT** [comment] 2016-07-20 20:32
Server down.

**Closed by MonkeyLeeT** 2016-07-20 20:32 UTC
