### ISSUE TITLE
Duplicate browser notification

### ISSUE THREAD

**Issue by tolinwei** [AHAAAAAAA/PokemonGo-Map#2529] opened 2016-07-29 03:15 UTC
I added expected Pokemons in the "Notify of Pokémon" area of left "Options" panel, whenever the desired Pokemon appears, the browser pops up the notification, this is great, however, there are duplicated notifications, sometimes it comes the first one, then three duplicated, sometimes there are more. 

Even when I close one of the notification panel (Chrome, on the top right side), it will pop up a new one instantly. In most of the times, there are three notification panels showing on top right of my screen (even the Pokemon has disappear), which is annoying.

## Expected Behavior

1. One notification per appearance
2. Don't show notification when the Pokemon disappear

## Current Behavior

Please refer to the first part "general summary", that's pretty clear.

## Possible Solution

I'm not sure the mechanism  of browser notification, maybe it's the nature drawback that we can't fix, so just open an issue here to get some more information.

## Steps to Reproduce (for bugs)

This is pretty common, it appears for every notified Pokemons.

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
Python 2.7.11 (default, Jun 17 2016, 20:01:51)
* Operating System and version (desktop or mobile):
Mac OS X El Capitan, 10.11.5
Chrome Version 51.0.2704.103 (64-bit) 
Safari Version 9.1.1 (11601.6.17)

**Comment by MonkeyGoneWIld** [comment] 2016-07-29 03:33
This has already been reported several times, its mostly due to Pokemon appearing because of lure

**Comment by commanderjsoc** [comment] 2016-07-29 03:34
this is a duplicate of #2374 and a whole bunch of other ones.  There is a fix coming is a future update

**Closed** 2016-07-29 03:37 UTC

**Comment by tolinwei** [comment] 2016-07-29 03:55
Thanks @MonkeyGoneWIld @commanderjsoc ，the new feature will come to develop branch first, right?

**Comment by commanderjsoc** [comment] 2016-07-29 03:56
correct  
  
  
![](https://link.nylas.com/open/6cbt55i9o2eqc9w5uoprvd3dv/local-538c26ce-
83a9?r=cmVwbHkrMDBjMTlhZGRiMWY1NWQ4ODgyZTg4ZTg2OTJkN2U1MTFhZTlhYWViODIzNjc4NjZjOTJjZjAwMDAwMDAxMTNiMjk1ZGI5MmExNjljZTBhMDcyY2M2QHJlcGx5LmdpdGh1Yi5jb20=)

  
On Jul 28 2016, at 8:56 pm, Wei Lin &lt;notifications@github.com&gt; wrote:  

> Thanks
[@MonkeyGoneWIld](https://github.com/MonkeyGoneWIld&r=cmVwbHkrMDBjMTlhZGRiMWY1NWQ4ODgyZTg4ZTg2OTJkN2U1MTFhZTlhYWViODIzNjc4NjZjOTJjZjAwMDAwMDAxMTNiMjk1ZGI5MmExNjljZTBhMDcyY2M2QHJlcGx5LmdpdGh1Yi5jb20=)
[@commanderjsoc](https://github.com/commanderjsoc&r=cmVwbHkrMDBjMTlhZGRiMWY1NWQ4ODgyZTg4ZTg2OTJkN2U1MTFhZTlhYWViODIzNjc4NjZjOTJjZjAwMDAwMDAxMTNiMjk1ZGI5MmExNjljZTBhMDcyY2M2QHJlcGx5LmdpdGh1Yi5jb20=)
，the new feature will come to develop branch first, right?

>

> --  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/AHAAAAAAA/PokemonGo-
Map/issues/2529#issuecomment-236088826&r=cmVwbHkrMDBjMTlhZGRiMWY1NWQ4ODgyZTg4ZTg2OTJkN2U1MTFhZTlhYWViODIzNjc4NjZjOTJjZjAwMDAwMDAxMTNiMjk1ZGI5MmExNjljZTBhMDcyY2M2QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe-
auth/AMGa3SzB7zG8sSs3KHfuG4odkwybCPtyks5qaXnbgaJpZM4JX1q5&r=cmVwbHkrMDBjMTlhZGRiMWY1NWQ4ODgyZTg4ZTg2OTJkN2U1MTFhZTlhYWViODIzNjc4NjZjOTJjZjAwMDAwMDAxMTNiMjk1ZGI5MmExNjljZTBhMDcyY2M2QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AMGa3dL3L6ugk-FDfgJJRgGZYLeBZw99ks5qaXnbgaJpZM4JX1q5.gif)
