### ISSUE TITLE
TypeError: 'ResultIterator' object is not iterable

### ISSUE THREAD

**Issue by Znuff** [AHAAAAAAA/PokemonGo-Map#790] opened 2016-07-21 08:56 UTC
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 14.04, x64

Installed version of Python:
2.7

### Steps to reproduce
1. Update to latest revision
2. Run
3.

### What have you tried?
1. Removing the PokeStops display fixed the issue

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

2016-07-21 11:54:35,096 [  runserver] [   INFO] Parsed location is: 44.4731/26.0790/0.0000 (lat/lng/alt)
2016-07-21 11:54:35,098 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 11:54:35,101 [   auth_ptc] [   INFO] PTC login for: XXX
2016-07-21 11:54:35,140 [  _internal] [   INFO]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2016-07-21 11:54:36,243 [   auth_ptc] [   INFO] PTC Login successful
2016-07-21 11:54:36,652 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-21 11:54:36,653 [     search] [   INFO] Scanning step 1 of 100.
2016-07-21 11:54:37,070 [     models] [   INFO] Upserting 80 pokestops
2016-07-21 11:54:37,859 [     models] [   INFO] Upserting 6 gyms
2016-07-21 11:54:37,871 [     search] [   INFO] Completed  1.00% of scan.
2016-07-21 11:54:38,872 [     search] [   INFO] Scanning step 2 of 100.
2016-07-21 11:54:39,231 [     models] [   INFO] Upserting 33 pokestops
2016-07-21 11:54:39,245 [     models] [   INFO] Upserting 4 gyms
2016-07-21 11:54:39,254 [     search] [   INFO] Completed  2.00% of scan.
2016-07-21 11:54:39,671 [     models] [   INFO] Get Pokemons for stamp: 2016-07-21 11:54:28.175000
2016-07-21 11:54:39,675 [  _internal] [   INFO] 188.241.144.243 - - [21/Jul/2016 11:54:39] "GET /pokemons/1469091268175 HTTP/1.1" 200 -
2016-07-21 11:54:39,723 [  _internal] [   INFO] 188.241.144.243 - - [21/Jul/2016 11:54:39] "GET /gyms HTTP/1.1" 200 -
[2016-07-21 11:54:39,709] ERROR in app: Exception on /pokestops [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ibm86/pogo/pogom/app.py", line 45, in pokestops
    return jsonify(Pokestop.get())
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 369, in dumps
    **kw).encode(obj)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 262, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 340, in iterencode
    return _iterencode(o, 0)
  File "/home/ibm86/pogo/pogom/app.py", line 80, in default
    return list(iterable)
TypeError: 'ResultIterator' object is not iterable

**Comment by MikeDX** [comment] 2016-07-21 08:59
dupe of #774 but probably fixed in the latest develop head.

**Comment by benemorius** [comment] 2016-07-21 08:59
duplicate of #774

**Comment by MikeDX** [comment] 2016-07-21 09:01
You are right, my branch was just out of date as I had rolled back to write that bug...

**Comment by evrardjp** [comment] 2016-07-21 09:05
A PR is there to test https://github.com/AHAAAAAAA/PokemonGo-Map/pull/777

**Closed** 2016-07-21 22:11 UTC
Labels: bug
