### ISSUE TITLE
Notifications keep on popping up for the same pokemon

### ISSUE THREAD

**Issue by OmarMustafa** [AHAAAAAAA/PokemonGo-Map#3258] opened 2016-08-03 03:26 UTC
They keep on popping up even after I click on them, or even after the pokemon disappears! The beep keeps playing!

Sometimes after the pokemon appears, the beeps keep on playing, even after the pokemon disappears.

Anyone else experiencing that?

I'm on OS X ElCapitan & Chrome version 51.0.2704.103 (64-bit)
Same think on Firefox 41.0.2

**Comment by zumbrunnen** [comment] 2016-08-03 06:40
Duplicate of #3237

**Closed** 2016-08-03 08:36 UTC
