### ISSUE TITLE
[request] option to change port number for webserver

### ISSUE THREAD

**Issue by mcmaxl** [AHAAAAAAA/PokemonGo-Map#36] opened 2016-07-17 21:15 UTC
Hi, an option to change port number would be awesome too!

**Comment by sykhro** [comment] 2016-07-17 21:18
Duplicate of #27 
GitHub issues are for bug reporting.
For general support, and feature request, join our discord server. To make bug reports easy to find and organized, we close issues that are deemed out of scope for GitHub Issues and point people to Discord.

**Closed by sykhro** 2016-07-17 21:18 UTC
Labels: invalid

**Comment by marauder37** [comment] 2016-07-18 02:04
What is this Discord thing? I tried to use that link to join, it says "The instant invite has expired or is invalid". For myself, I was ok with having feature requests here

**Comment by JZ6** [comment] 2016-07-18 03:52
updated the link : use this invite from now on, (other one expired)
https://discord.gg/NZEtnBJ

**Comment by JZ6** [comment] 2016-07-18 03:52
I ll add a discord link to the wiki link them there next time,
there are also common fixes that i put there
