### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#2513] opened 2016-07-28 22:30 UTC
http://prntscr.com/bytolk

**Comment by DomGrieco** [comment] 2016-07-28 22:32
It means the servers are struggling to keep up with all the request. That or they found a way to throttle us without affecting game performance!

**Comment by DoraKlikOpDora** [comment] 2016-07-28 22:33
At the bottom of the screenshot your answer is, Niantic is overwhelmed by all global requests.

**Comment by DomGrieco** [comment] 2016-07-28 22:34
What worries me is the status of the servers are fine according to other sources.

**Comment by Valenteen** [comment] 2016-07-28 22:38
if you change it to -t 1
it works... slowly, but it works.

**Comment by IronChroni** [comment] 2016-07-28 22:41
same here, i have a feeling we're being throttled fellas

**Comment by Paralysing** [comment] 2016-07-28 22:43
Can confirm, for me, anything over -t 4 causes the error to appear.

**Comment by DomGrieco** [comment] 2016-07-28 22:46
Even with it set to 1 thread I'm still seeing the error when I have multiple searchers running. I wouldn't be surprised if they are throttling request by IP.

**Comment by IronChroni** [comment] 2016-07-28 22:47
Yeah Dom, looks like per IP, just tried the -t 2, and still no bueno , but i have roughly 6 searchers going

**Comment by theblackmarmoset** [comment] 2016-07-28 22:48
What do you mean throttling requests?  I still don't know what that means man.

**Comment by Paralysing** [comment] 2016-07-28 22:50
When your bot/map scanner sends more than a certain number of requests a second, the niantic servers block them, which is what throttling requests is.

**Comment by IronChroni** [comment] 2016-07-28 22:51
hmmm even with one scanner, and -t 1 , they are all failing.

**Comment by DomGrieco** [comment] 2016-07-28 22:51
It's really the only solution I can think of to blocking us out while not affecting game play.

**Comment by IronChroni** [comment] 2016-07-28 22:52
we all knew this day would come lol

**Comment by Paralysing** [comment] 2016-07-28 22:53
Right now, on -t 3, 1/4 of my search threads fail, but the other ones still work.

**Comment by IronChroni** [comment] 2016-07-28 22:53
pokevision and others are also failing, not sure why they would use ptc tho, its worthless

**Comment by Paralysing** [comment] 2016-07-28 22:53
Both google and ptc are experiencing this issue though.

**Comment by IronChroni** [comment] 2016-07-28 22:54
well ptc logins are down, so if you are using that, you won't even get this far

**Comment by OmecronBlazor** [comment] 2016-07-28 22:55
I'm slowly getting some responses. I'm using one tracker with -t 1.

**Comment by Vega2015** [comment] 2016-07-28 23:00
-t 1 -sd 0.2

will solve the problem

**Comment by rayuki** [comment] 2016-07-28 23:00
i highly doubt its trottling or any bullshit. servers have been flaky all night long. 

http://ispokemongodownornot.com/ says all PTC login servers down. all my accounts are PTC. i tried with a few google accounts and no issues at all. im running -t8 on 40 PTC accounts.

**Comment by DomGrieco** [comment] 2016-07-28 23:02
I'm using google accounts on all 22 of my scanners and I'm slammed with errors.

**Comment by DomGrieco** [comment] 2016-07-28 23:06
@Vega2015 I tried that I'm its scanning faster but still the same amount of errors.

**Comment by IronChroni** [comment] 2016-07-28 23:10
i have about 6 on one vm, and about 3 on another vps , and 2 on another, and all of them are crapping out

**Comment by Paralysing** [comment] 2016-07-28 23:12
Seems like -t 3 -st 1.7 gets rid of the error, but it also slows scans by a lot.

**Comment by moggd** [comment] 2016-07-28 23:38
I've been getting all kinds of weird errors in the past few hours.  Getting a GET_MAP_OBJECTS failed in parse_map from models.py

**Comment by Dagothur** [comment] 2016-07-29 00:53
Looks like they throttled requests per account. From what little testing I did I believe the maximum thread count per account is -t 2.

Is there an easy way to supply a list of accounts to shard out a larger -st area so that this change isn't relevant? Is the beehive generator the solution?

**Comment by Paralysing** [comment] 2016-07-29 01:03
Not completely sure if the throttled request is by account, ip, or both, could someone test this?

**Comment by Dagothur** [comment] 2016-07-29 01:05
My testing wasn't rigorous at all, but:

I was able to run two accounts on the same IP with -t 2 95%+ of updates worked

When I ran a single account at -t 3 it dropped updates

**Comment by Niksunen** [comment] 2016-07-29 01:12
Well hope not :D i have now 10 instances running, all of them uses t-50  and -st40 so i have 500 threads.
I have 4 servers. One is frontend and is only server for the map. 2 of them are servers for "instances" they run python and grab pokemons locations and write them mysql database, which is number 4 server. And frontend server reads locations by mysql database and draws them in the map.

Servers detail:
Dedicated CPU	28.8 GHz (16 x 1.80 GHz)
RAM	16 384 MB
Bandwidth limit is 8.0 TB / month (transferred 0.4 TB this month = 284.2 GB in + 128.0 GB out) (and these is just by 3 days of pokemon scanning :D )
 
 And i was planning to double it 20 instaces by weekend.  If there really is "thread throttle" that sucks :D

**Comment by Paralysing** [comment] 2016-07-29 01:12
When I run 2 instances on a single ip with -t 2, one of the instances worked fine, but the other one timed out, but when I run 2 instances for the on separate ip's, they work fine. All of the tests were ran with the same account, will test separate accounts next.

**Comment by Dagothur** [comment] 2016-07-29 01:17
If the throttling is by only accounts, we simply need the ability to supply a list and have the workload split. 

I think some modifications to a generated beehive_builder.sh and generated beehive.sh can do this quick and dirty while someone creates a more elegant solution

**Comment by Paralysing** [comment] 2016-07-29 01:19
Confirmed, the throttling is linked to accounts, not ip, tried 2 instances with different accounts on -t 2 and it worked.

**Comment by Dagothur** [comment] 2016-07-29 01:26
Cat and mouse begins I guess. Bypassing this account issue seems quite trivial whereas IP limitations will require people to have an appropriate number of IPv4s...

**Comment by DomGrieco** [comment] 2016-07-29 01:27
When you think about it throttling by IP wouldn't be a good idea. What if you have a bunch of people sharing the same WiFi. No go..

**Comment by Dagothur** [comment] 2016-07-29 01:28
Yeah, very true.

**Comment by basepi** [comment] 2016-07-29 01:32
I'm finding I can do `-sd .65 -t 2` with no throttling. `-sd .6` was throttling slightly, but still making it through. At that rate I can scan a `-st 8` in just over a minute. Sad, I was doing a 32 in under 3 minutes before....

Guess I'll have to spin up more ptc accounts. Anyone know how to do it quickly? Manually it was taking me a few minutes per account which is painful.

**Comment by DomGrieco** [comment] 2016-07-29 02:28
@AHAAAAAAA What do you think?

**Comment by wolf5x** [comment] 2016-07-29 02:38
'Niantic servers under heavy load. Waiting before trying again' most likely happens right after restarting at a new location.

Tried with -st 10 and config['REQ_MAX_FAILED']=5 and it failed in the first few seconds. And it hardly recover later (should it?).

Set config['REQ_MAX_FAILED']=20 (or larger) to get around this error in the first few seconds. And everything was fine later.

Guess it is because create_search_threads() creates all the threads at once at startup. All the threads send their first requests simultaneously, thus it overloads easily. But afterwards, there is little chance that all threads send requests at the same time.

**Comment by WiseClock** [comment] 2016-07-29 02:56
@wolf5x I just tested it.  Yeah it does not stop anymore, but the scan speed is actually the same as setting it to -t 3, all the other threads will fail.  Guess they limited the search frequency.

**Comment by DomGrieco** [comment] 2016-07-29 03:04
I can do -t 3 at a delay of .91 with 0 errors.

**Comment by jlroettger** [comment] 2016-07-29 03:11
Would be great to have a way to pool multiple account credentials for the same search area

**Comment by jacobalberty** [comment] 2016-07-29 03:12
jlroettger, sounds like a good modification to add to the beehive, modify it to use a pool of credentials.

**Comment by max1c** [comment] 2016-07-29 03:21
Set config['REQ_MAX_FAILED']=20
 
 This works. 

Is there a way start the scan from the end of the -t instead of the starting location?

**Comment by tabletyrant** [comment] 2016-07-29 04:05
Can anyone tell me where to input config['REQ_MAX_FAILED']=20 ? I didn't see anything on the wiki related to it.

**Comment by WiseClock** [comment] 2016-07-29 04:06
__init__.py

**Comment by DomGrieco** [comment] 2016-07-29 04:07
What exactly is the `config['REQ_MAX_FAILED']=20` doing?

**Comment by WiseClock** [comment] 2016-07-29 04:08
The searcher stops when you encounter 20 'request failed' errors.

**Comment by DomGrieco** [comment] 2016-07-29 04:09
@WiseClock does it stop permanently or for pick back up after so long?

**Comment by WiseClock** [comment] 2016-07-29 04:11
It does not stop permanently for me, but it holds for a longer time to retry.  Say if you set the max to 1000, it'll keep going with the errors spamming...

**Comment by DomGrieco** [comment] 2016-07-29 04:13
I've been creating new accounts for each searcher to have its own account. I haven't been running into any more errors but getting all these accounts is really time consuming.

**Comment by oceanor** [comment] 2016-07-29 07:02
pokèvision is working properly, how the hell?

**Comment by mattrat88** [comment] 2016-07-29 07:09
Will this issue be fixed ? Bypassed like wth I felt this made up for the step issue ...

**Comment by Paralysing** [comment] 2016-07-29 07:12
The map still makes up for the 3 step issue as long as you set -t to 3 or less. I submitted a feature request, #2546 which should fix throttling, since the throttling of requests is per user, not ip.

**Comment by RemyLebeau** [comment] 2016-07-29 07:28
How can I change the -t value fora heroku deployment?  There isn't a config key in the settings for it ... ?

**Comment by Paralysing** [comment] 2016-07-29 07:34
I believe that -t usually defaults to 1, doesn't seem like you can change it in heroku.

**Comment by RemyLebeau** [comment] 2016-07-29 07:36
Can you direct me where to change the default value then ?  I'll modify it in my fork and update heroku!

**Comment by marauder37** [comment] 2016-07-29 07:38
someone informs me that the heroku deployment has an extra-flags thing

**Comment by RemyLebeau** [comment] 2016-07-29 07:42
Thanks.

For anyone else wondering, under Settings, you need to create a a new Config Var as follows:

EXTRA_ARGS   with value -t 3

**Comment by Paralysing** [comment] 2016-07-29 07:43
Oh thanks, I didn't know that existed, I hard coded my thread count before.

**Comment by GareRam** [comment] 2016-07-29 07:51
Sorry for asking, but is the threaded bug in windows fixed already? Or should windows users still be running -t 1 instead of the now max -t 2?

I used to have my windows server do the webinterface, and my mac scan with 25 threads, but that's over now... so I am going to make a honeycomb pattern for my city (and friends) :)

**Comment by mattrat88** [comment] 2016-07-29 08:00
Do I just enter into the terminal along with my other commands ? Like add it anywhere -t 3 -l somewhere , somewhere

**Comment by RemyLebeau** [comment] 2016-07-29 08:13
Yup.

**Comment by BlacKZoNex** [comment] 2016-07-29 09:55
1 PTC account per process with -t 4 an -sd 2 works perfect without any errors.

**Comment by Shinitas** [comment] 2016-07-29 13:26
I tried now with master version:
-t 3 and -sd 1 works fine, too

**Comment by DomGrieco** [comment] 2016-07-29 14:48
I noticed that some of my accounts aren't able to log in now. Although, when I boot up android and test the login on my local PC I can log in. Also, if I proxy a different IP and test logging into that one account that was saying "Failed to log in trying again in 5 seconds" it works. Are they now only allowing so many connections per IP? They are making this really difficult now.

**Comment by Dagothur** [comment] 2016-07-29 15:36
I have 13 workers from the same IP no problem.

**Comment by DomGrieco** [comment] 2016-07-29 15:39
I just realized its the password on some of the new accounts I made. They have special characters that the script does not like.

**Comment by basepi** [comment] 2016-07-29 18:27
So far I have 6 workers per box doing `-t 1 -sd .3 -st 10`, 26 workers total at the moment, all feeding back into a central server which hosts mysql and the web interface. Everything going smoothly, no throttling issues that I can detect.

**Comment by Dagothur** [comment] 2016-07-29 18:31
I think that may be the fastest suggested yet. 3.33 scans a second.

**Comment by DomGrieco** [comment] 2016-07-29 18:34
@basepi Thanks for the info. I've just been using `-t2 -sd 1 -st 6`

**Comment by mattrat88** [comment] 2016-07-29 18:39
How would I run two or more accounts at a time ? And how would I make them search properly ? I've had almost all of this from the get go but now I'm just stumped lol

**Comment by DrTeej** [comment] 2016-07-29 18:50
@basepi Are you using multiple accounts or nah?

I'd like to have a total of 4-5 locations scanned. I assume I can still do one box.

**Comment by DomGrieco** [comment] 2016-07-29 18:51
You have to use multiple accounts since last night.

**Comment by basepi** [comment] 2016-07-29 18:52
@mattrat88 https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop/Tools/Hex-Beehive-Generator will generate locations in a hex pattern to cover larger areas with multiple processes. I did 10 steps and 3 leaps which resulted in 19 workers covering a fairly large area.

You'll have to give a different account to each worker.

@DrTeej separate account per worker. I spent a half hour creating 32 ptc accounts during lunch.

**Comment by DomGrieco** [comment] 2016-07-29 18:52
@mattrat88 `python runserver.py -a google -u USERNAME -p PASSWORD -l "LOCATION, LOCATION`

**Comment by DomGrieco** [comment] 2016-07-29 18:54
@basepi I created google apps for work account on the 30 day trial to get 10 gmails, then I made 10 PTC accounts with those gmails. I set a alert in my phone calendar to remind me to cancel google apps in 29 days. Haha

**Comment by DrTeej** [comment] 2016-07-29 18:56
@basepi  Does it matter if you use Google or PTC accounts? I've noticed PTC down more often.

So, just to confirm. Single Thread. 10 steps, and a .3 scan delay? 

Doesn't matter on external IP's?

**Comment by mattrat88** [comment] 2016-07-29 18:58
How do I get the beehive thing running , can I use my google key instead of long and lat or could I use my location,location

**Comment by basepi** [comment] 2016-07-29 18:59
Here's a hack for those creating lots of PTC accounts. Gmail accounts have a little known feature where you can add an arbitrary string onto your email address. Just use `+<string>` on the end before the @ symbol.

For example, if you have myemail@gmail.com you can do myemail+ptc1@gmail.com and that will still come to your email. Just increment the number for each account.

You can also use this when you give your email to different websites, creating a unique email for each website, then you can use gmail filters to filter on those unique emails.

@DrTeej PTC is just easier to create a bunch of accounts quickly (for me, anyway). And it's usually up, but yes, goes down sometimes.

Those settings are what I've found to be best. I can complete a 10-step hexagon in a timely manner that way. Obviously eventually you'll hit the limits on your box or your database so your mileage may vary. It appears external IP doesn't matter (yet).

@mattrat88 beehive relies on lon/lat. You can get that by clicking on an area on maps.google.com, it will show the lon/lat for that spot.

**Comment by DrTeej** [comment] 2016-07-29 19:01
Thanks, @basepi !!!

**Comment by mattrat88** [comment] 2016-07-29 19:05
Much appreciated , so how do add this code into the files I already have ? Xcode ?

**Comment by basepi** [comment] 2016-07-29 19:07
@mattrat88 Not sure which guide you used. But if you just get the latest develop code it should be in there, in the Tools directory. Actually I think it's in master now as well.

**Comment by mattrat88** [comment] 2016-07-29 19:16
I had the new one but clicked the link and just copied the code into what I had

**Comment by mattrat88** [comment] 2016-07-29 19:17
That should work I assume now I gotta figure it all out , your a boss tho I appreciate the fast responses :)

**Comment by mattrat88** [comment] 2016-07-29 19:21
I'm pretty sure it's all just added with the code to initiate it right ahhh trail and error anyways props to all of you working hard on this your the real mvps considering niantic can't even get there three step issue resolved

**Comment by DomGrieco** [comment] 2016-07-29 19:43
I have 51 workers running with `-t2 -sd 1 -st 5` on Digital's Ocean $20 droplet. CPU usage around 60-70%.

**Comment by mattrat88** [comment] 2016-07-29 20:18
I'm very confused how to run this beehive command line with the others I'm confused :/ I'm on a Mac too just cannot figure it out derp

**Comment by DoraKlikOpDora** [comment] 2016-07-29 20:22
@mattrat88 already checked the wiki page about beehive?

https://www.jonaharagon.com/PoGoMapWiki/#!beehive.md

**Comment by tabletyrant** [comment] 2016-07-29 22:19
Sorry for the likely noob question, but how do you set -sd to a value other than 1? Mine won't accept anything other than an integer.

**Comment by Paralysing** [comment] 2016-07-29 22:21
I'm pretty sure you can set -sd to any number.

**Comment by Paralysing** [comment] 2016-07-29 22:22
Pretty sure you can set -sd to any number, decimals work too, as long as you don't hit 3 requests a second.

**Comment by mattrat88** [comment] 2016-07-30 01:54
Import error no modual named latlon ?

**Comment by Paralysing** [comment] 2016-07-30 01:55
pip install latlon

**Comment by tabletyrant** [comment] 2016-07-30 02:50
I get an error "invalid int value" when using a decimal for -sd.

**Comment by Paralysing** [comment] 2016-07-30 03:40
What branch are you on? On develop, I'm able to input a decimal.

**Comment by tabletyrant** [comment] 2016-07-30 04:57
I was on the master branch. Switching to develop fixed it. Thanks!

**Comment by Skalander97** [comment] 2016-07-30 10:51
After reading this whole thread my thought for the solution must be that we need to create more pokemon go accounts and assign them to work together? I am no programmer so I have little experience of this and no idea where and how to even begin with this process.

And I guess there is no one that would be so kind to setup a worker or two in my small town here in Sweden?

**Comment by Paralysing** [comment] 2016-07-30 15:59
@Skalander97 I might be able to setup an instance for you, depends on how far you would want me to set the scan radius.

**Comment by Skalander97** [comment] 2016-07-30 17:12
@paralysing I only need a range of like 7-8, its a very small town :) That would be so kind of you if you could do that!

**Comment by Paralysing** [comment] 2016-07-30 17:15
@Skalander97 Which town, or lat/long should I scan?

**Comment by Skalander97** [comment] 2016-07-30 17:18
Its called "Huddinge" so type "Huddinge" in the location input and it should be working fine

**Comment by Skalander97** [comment] 2016-07-30 17:22
@Paralysing If that doesnt work i can look up the lat/long for you :)

**Comment by Paralysing** [comment] 2016-07-30 17:27
@Skalander97 Setting up the server now, do you need search location or can I set it as fixed?

**Comment by Skalander97** [comment] 2016-07-30 17:31
Im not sure what that does so set it as fixed I guess. Youre a hero @paralysing !

**Comment by Paralysing** [comment] 2016-07-30 17:59
Currently, the site is at https://huddinge.skeptical.cf, but nothing is showing up, I'll try to reinstall and run grunt.

**Comment by Skalander97** [comment] 2016-07-30 18:01
@Paralysing No hurries mate, take the time you need. I have no time to play today anyways. Im just so happy that youre helping me :)

**Closed** 2016-07-30 18:01 UTC
Labels: not an issue; servers are down

**Comment by Paralysing** [comment] 2016-07-30 22:25
@Skalander97 Fixed, running server on -t 5 -sd 1.2 -st 10 -fl

**Comment by Skalander97** [comment] 2016-07-30 22:32
@Paralysing Thank you very much! I'll be in touch in this thread if anything happens. But it looks like its running extremely well. I cant thank you enough for this! :)

**Comment by itgsod-philip-skalander** [comment] 2016-08-01 10:14
@Paralysing Is there someway I can write to you outisde this thread? Like maybe through email, skype or steam?

**Comment by licklake** [comment] 2016-08-01 10:55
-t 5 -sd 2 -st 5 works fine for me
