### ISSUE TITLE
[Feature Request] Implement multiple ptc/google accounts for the scanner

### ISSUE THREAD

**Issue by Paralysing** [AHAAAAAAA/PokemonGo-Map#2546] opened 2016-07-29 05:44 UTC
**Expected Behavior**
The thread count should be able to be set to any number.

**Current Behavior**
Recently, due to Niantic throttling requests per account to 3 requests per second, the -t cannot be set higher than 3 without a scan delay.

**Possible Solution**
To be able to send more than 3 requests a second, you could implement multiple (ptc/google) accounts. Since the throttle of requests is per account, you could modify the beehive scanner to alternate between accounts every 3 requests. The more accounts added, the more requests you could send.

**Steps to Reproduce (for bugs)**
1. Set -t higher than 3, don't set an -sd

**Context**
For data mining and scanning larger areas (-st 50) -t 3 isn't as effective as, for example, -t 10. To speed up scanning of a large area, the threads should be set higher than 3.

**Your Environment**
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu 14.04 Server

**Comment by mortasgus** [comment] 2016-07-29 07:52
@Paralysing 
The scan write the search result in pogom.db and the web server read it.
So you can launch multiple scan at different location and different user with the --no-server switch.
in ubuntu/linux, you have openvt
sudo openvt -c7 -- python /path/to/runserver.py --no-server -user1 -other command line ....
sudo openvt -c8 -- python /path/to/runserver.py --no-server -user2 -other command line ....
........
openvt -cX -- python runserver.py -userX -command line ....

you don't use the other terminal, you can use -c2 to -c6

**Comment by shiona** [comment] 2016-07-29 08:08
@mortasgus The bad thing about this is that the two processes will not share search_queue, so you either need to give each process a small portion of the large area (and calculate manually the scan positions) or risk having the processes just scan the same places.

I believe I have a working branch that does work with multiple accounts, splitting search threads between them. The bad thing is that it completely breaks the command line compatibility with master.

As it is, parameters --auth --username and --p take one string each. This works nicely. If we try to add more accounts, one possibility could be:
./runserver -a ptc -u user1 -p password1 -a google -guser1 -gpassword1 -a ptc -u user2 -p password2
I believe I'm not the only one who dislikes this, so for now I'm going with
./runserver -a ptc:user1:password1 google:guser1:gpassword1 ptc:user2:password2
which makes it much clearer which credentials should work together.

I'll keep testing it for a while and once I'm happy enough with it I'll create a fork and a PR.

Any feedback is appreciated.

**Comment by shiona** [comment] 2016-07-29 08:35
Please do test this and if you have any suggestions let me know.

https://github.com/shiona/PokemonGo-Map

**Comment by Dragonprovidence** [comment] 2016-07-29 08:47
@Paralysing, that's an interesting idea. I hadn't thought about spiting one search circle among accounts. I went a different route to alleviate this current throttling issue. I implemented a queue so that the next location post call is sent to the server that hasn't moved the longest.

@shiona Definitely interested in testing that branch out.

**Comment by shiona** [comment] 2016-07-29 09:28
Btw what's the policy on pull requests?

Do I discuss the possible issues here using my own fork and
make a pull request only when I feel the code is completely 
ready, or should I make a pull request first and get feedback there?

**Comment by remie2000** [comment] 2016-07-29 09:29
@shiona I am willing to test this but could you explain how to use the commandline.

My current commandline:

`screen -dmS PokemonGoMap python /root/PokemonGo-Map-master/runserver.py -u Username -p password -st 15 -k APIkey -l "Location" -P 8080 -H 0.0.0.0 -t 3 -sd 1 -td 1 -ld 1`

**Comment by shiona** [comment] 2016-07-29 09:35
@remie2000

remove -u and -p parameters and replace them with an -a that takes "auth_provider:username:password" as value. So for your command I think the corresponding command would be: 
`screen -dmS PokemonGoMap python /root/PokemonGo-Map-master/runserver.py -a ptc:Username:password -st 15 -k APIkey -l "Location" -P 8080 -H 0.0.0.0 -t 3 -sd 1 -td 1 -ld 1`

This branch however will not help you in any way unless you make another account for scanning. Say that would be "nameUser" with password "wordpass", then the command to use both accounts for scanning would be:

`screen -dmS PokemonGoMap python /root/PokemonGo-Map-master/runserver.py -a ptc:Username:password -a ptc:nameUser:wordpass -st 15 -k APIkey -l "Location" -P 8080 -H 0.0.0.0 -t 6 -sd 1 -td 1 -ld 1`

Note the doubled number of threads in the latter command. The scan threads get split between accounts.

**Comment by oceanor** [comment] 2016-07-29 09:45
great commit, you can also put account with a single -a

example:

-a ptc:acc1:pass1 ptc:acc2:pass2 ptc:acc3:pass3

**Comment by remie2000** [comment] 2016-07-29 10:38
@shiona My account got locked after 5 attempts :( I know 100% sure it is correct.

My password has a `_` at the end of the password. Could this be the cause?

**Comment by shiona** [comment] 2016-07-29 10:52
@remie2000 I created accounts with a passwords ending in `_` and had no problems. You wouldn't happen to have colons (`:`) in the username or password somewhere?

**Comment by remie2000** [comment] 2016-07-29 11:05
@shiona No : in the password or username.
Is there a way to send you private message so you can have my original commandline

**Comment by shiona** [comment] 2016-07-29 11:29
I don't see why you should trust me more than this discussion. Let's first try figuring this out.

- Are you sure you pass the correct authentication provider (ptc or google) as the first value
- Have you tried your username and password combo with the AHAAAAAAA/master branch? if either the password or username contain anything that would be a problem with command line (such as `'`, `"`, `|`, `*` etc.) then those credentials should not work with that branch either.

**Comment by remie2000** [comment] 2016-07-29 11:34
I tested it with the following user: -a ptc:remie1995:Beheer001 (I will change password within 1 hour)
This is confirmed working with V2.1.0 master branch

```
2016-07-29 13:36:12,695 [     runserver] [   INFO] Parsed location is: 52.1729/5.2863/0.0000 (lat/lng/alt)
2016-07-29 13:36:12,701 [        search] [   INFO] Search loop 0 starting
2016-07-29 13:36:12,701 [        search] [   INFO] Attempting login to Pokemon Go.
2016-07-29 13:36:12,702 [      auth_ptc] [   INFO] PTC login for: remie1995
2016-07-29 13:36:13,363 [      auth_ptc] [   INFO] PTC Login successful
2016-07-29 13:36:13,671 [        search] [   INFO] Login to Pokemon Go successful.
```

**Comment by shiona** [comment] 2016-07-29 11:42
@remie2000 
At the moment I'm having a conversation about (probably) the same problem in two places. Here's a link to what I wrote to another guy: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2568#issuecomment-236159593

**Comment by carze** [comment] 2016-07-29 11:44
Right... completely forgot that '!' would get eaten up by the shell. That was my fault. 

I am passing in multiple accounts and it seems like only one account is getting used at the moment but let me see if I can verify that this is occurring.

**Comment by shiona** [comment] 2016-07-29 11:54
@carze It seems I have made a mistake myself. It seems @oceanor's way of parameter passing is the only correct one. So just one `-a` followed by one or more auth strings. as in https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2546#issuecomment-236139498.

**Comment by carze** [comment] 2016-07-29 12:02
@shiona that did the trick. Thanks!

Seems like there might be some sort of database locking issue?

'''
2016-07-29 13:57:31,939 [           app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sleazyc/pokemongo-map-multiacc/pogom/app.py", line 61, in raw_data
    d['pokestops'] = Pokestop.get_stops(swLat, swLng, neLat, neLng)
  File "/home/sleazyc/pokemongo-map-multiacc/pogom/models.py", line 150, in get_stops
    for p in query:
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/sleazyc/.pyenv/versions/pokemongo-map-multiacc/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
'''

Is it normal behavior for the map to be populated seemingly all at once as opposed to the step-by-step process the non multiple-accounts version seems to operate by?

**Comment by shiona** [comment] 2016-07-29 12:12
I have no idea what's happening there, I haven't seen anything like that. What SQL are you using? Are you by any chance using the same database in multiple instances of `runserver.py`?

My program should not change the ordering of scanned locations (although one account may get frozen so that some locations may get skipped.)  Here's one of my runs:
![4 accounts, 12 threads](https://cloud.githubusercontent.com/assets/1516312/17244481/c43c470e-558a-11e6-8b29-cdedaf0b6ae4.png)
 Do note that this is running on the master branch, I haven't worked out running the dev branch map. I hope it doesn't matter.

**Comment by photex12** [comment] 2016-07-29 12:40
@oceanor "-a ptc:acc1:pass1 ptc:acc2:pass2 ptc:acc3:pass3"

Does that work out of the box?
Or do I need to alter some code to scan a large area with multiple accounts (does it automaticly devide sections between the accounts??)

**Comment by carze** [comment] 2016-07-29 13:04
@shiona for the time being I am using the master branch and am using the sqlite database. I do have MariaDB setup on this machine but wanted to see how it performed at the moment.

Seems to be working ok aside from the database locking issue that I guess I can see if it occurs when plugging into MariaDB. Running with four accounts, 12 threads and a step limit of 25.

Going to play around and see how this performs with more accounts and higher step limits.

**Comment by shiona** [comment] 2016-07-29 13:08
@carze I ran sqlite with the same 4 accounts and 12 threads with no problem (that screenshot is from that run). Sorry, I'm not really good with ORMs, so I'm not much of a help here.

@oceanor There shouldn't be a need for you to modify any code. Just pull the correct branch and change the parameters.

**Comment by remie2000** [comment] 2016-07-29 13:34
@shiona 

I just can't get this script working.
Tried to quote -a ptc:acc1:acc1 ptc:acc2:acc2 in multiple ways but no prevail.
Also put -a part behind and directly after runserver.py in commandline but same errors.

**Comment by photex12** [comment] 2016-07-29 13:41
@shiona 
so if I start the runserver.py with this parameters -a ptc:acc1:pass1 ptc:acc2:pass2 ptc:acc3:pass3" (of course correctly filled in) the server divides the scanning of sectors between the accounts used.

What I don't want is 2 accounts scanning the same sectors within my search field (-st)

**Comment by commanderjsoc** [comment] 2016-07-29 13:57
Is This too late to suggest scanning using this method? #1056 Seems like it would be faster and way more efficient.

**Comment by commanderjsoc** [comment] 2016-07-29 14:03
We would scan for 1 hour using this method, but then the search would switch into spawnpoint mode where the workers would check the spawn point right after they spawn something in. What do you think, @AHAAAAAAA @JZ6 ?

**Comment by shiona** [comment] 2016-07-29 14:11
@photex12 
That is exactly what the code was written for.

@commanderjsoc
How the scanning works is that there is one master thread that creates (and updates) a queue that contains locations to scan and a bunch of worker threads that just pick whatever is in that queue and make a query on that position from niantics servers.

My code has to do only with how worker threads are initialized and how they choose where to send the query. This code has nothing to do with how to choose the locations to scan. Therefore any code that would implement what was requested in #1056 should work with my code without (at least major) conflicts.

**Comment by chbiel** [comment] 2016-07-29 14:18
@shiona I am currently testing your PR but I cannot get it work.
Used command:
`python runserver.py -a ptc:iamtrainer1:MyPassword12345 -t 3 -st 15`
All other setting (like position, api-key) are present in the config/config.ini
username and password are commented out in config.ini

Now I get the following error with your branch:
> Could not retrieve token: Your username or password is incorrect. You have 4 attempts left before you will be locked out of your account for 15 minutes.

Using an older develop from yesterday, everything works fine with exactly the same credentials. (usename and password only has [A-Z-a-z0-9])

I do not use your master but your develop.

any idea?

**Comment by shiona** [comment] 2016-07-29 14:32
@chbiel No idea, sorry.

**Comment by chbiel** [comment] 2016-07-29 15:54
@shiona 
fyi: the problem is, that I give a [A-Za-z0-9] password on the command line, but in AuthPTC the resulting password that is submitted to the api is fully lowercase...

I pulled the current develop from upstream and everything works fine.
I searched a bit, but I didn't found a place where that password could get modified.

**Comment by shiona** [comment] 2016-07-29 15:56
@chbiel oh crap I'm an idiot. Thank you!

**Comment by chbiel** [comment] 2016-07-29 15:57
@shiona hehe, no problem

**Comment by ecrouch** [comment] 2016-07-29 16:05
@shiona So I cloned your branch but for some reason I can't get my map to appear. I've been using an older dev branch from 7/25 (forget version). The workers are working, dropped data is minimal with 3 accounts and -t 6 -sd 1 -td 1 -ld 1. Any clue why my map doesn't appear in your branch but does if I clone Master or use my old dev branch? Is there something I'm forgetting to update here?

**Comment by chbiel** [comment] 2016-07-29 16:10
@shiona thanks, now its working :)

**Comment by shiona** [comment] 2016-07-29 16:12
@ecrouch I think they now assume you run grunt to generate the css/js files (https://www.jonaharagon.com/PoGoMapWiki/#!Development.md)
Other than that you can use my master branch once I push the same minor fix to that branch too.

**Comment by ecrouch** [comment] 2016-07-29 16:13
@shiona well that's what I get for not following this thread as close as I should. I'll go get the grunt work done.

**Comment by chbiel** [comment] 2016-07-29 16:16
@shiona i can confirm an earlier comment a read, that both are logged in but only one is searching (as it seems).

there are 3 log outputs at max per second

`2016-07-29 18:15:03,747 [        models] [   INFO] Upserted 0 pokemon, 2 pokestops, and 0 gyms
2016-07-29 18:15:03,767 [        models] [   INFO] Upserted 0 pokemon, 2 pokestops, and 0 gyms
2016-07-29 18:15:07,435 [        models] [   INFO] Upserted 1 pokemon, 2 pokestops, and 0 gyms
2016-07-29 18:15:07,442 [        models] [   INFO] Upserted 0 pokemon, 2 pokestops, and 0 gyms
2016-07-29 18:15:07,478 [        models] [   INFO] Upserted 0 pokemon, 8 pokestops, and 3 gyms
2016-07-29 18:15:08,626 [        models] [   INFO] Upserted 1 pokemon, 8 pokestops, and 3 gyms
2016-07-29 18:15:08,967 [        models] [   INFO] Upserted 0 pokemon, 7 pokestops, and 3 gyms
2016-07-29 18:15:08,978 [        models] [   INFO] Upserted 0 pokemon, 7 pokestops, and 3 gyms
2016-07-29 18:15:12,634 [        models] [   INFO] Upserted 0 pokemon, 6 pokestops, and 2 gyms
2016-07-29 18:15:12,649 [        models] [   INFO] Upserted 1 pokemon, 6 pokestops, and 2 gyms
2016-07-29 18:15:12,706 [        models] [   INFO] Upserted 1 pokemon, 9 pokestops, and 3 gyms
2016-07-29 18:15:13,846 [        models] [   INFO] Upserted 1 pokemon, 10 pokestops, and 3 gyms
2016-07-29 18:15:14,163 [        models] [   INFO] Upserted 0 pokemon, 10 pokestops, and 3 gyms
2016-07-29 18:15:14,183 [        models] [   INFO] Upserted 0 pokemon, 10 pokestops, and 3 gyms
`

**Comment by shiona** [comment] 2016-07-29 16:20
@chbiel the number of threads you give it as a parameter get split between accounts. so with -t 3 and two accounts one account gets two threads and one gets just one. As it stands you should set -t to  3*number of accounts

**Comment by chbiel** [comment] 2016-07-29 16:21
@shiona I did that `-st 15 -t 6` with two acounts results in the above log

as stated before, I also cannot see the map

**Comment by carze** [comment] 2016-07-29 16:21
I'm running with 6 accounts now and 20 threads at a step limit of 25 and feel like I am hitting some sort of diminishing return. If I can get around to it maybe I can get some sort of raw metric to prove this but the scanning hasn't seemed to get any better with a new account added or more threads thrown at it. Just my small observation from running most of the day.

**Comment by shiona** [comment] 2016-07-29 16:35
@chbiel are you using `-a ptc:acc1:pass1 -a ptc:acc2:pass2` or `-a ptc:acc1:pass1 ptc:acc2:pass2`.
For whatever reason if I give another `-a` with a different account pythons argparse forgets what it had collected earlier. It sounds like this might be the problem. About the map not showing: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2546#issuecomment-236223585

@carze 
6 accounts and 20 threads sounds like it will hit the throttling limit of 3 threads per account. 
That might make it even slower than 6 accounts and 18 threads. I don't know. 
And it's inevitable that adding accounts will end up with diminishing returns. 
Moving from 1 to 2 accounts doubles the scanning speed, but going from 5 to 6 accounts only adds an extra 20% power. 

Moreover it might be that niantic has, or will implement IP-based throttling in addition to 
the current accout-based one.

**Comment by a-moss** [comment] 2016-07-29 16:43
@shiona I can confirm, at this point, that IP-based throttling has not been added. Let's hope that they don't add it in the near future.

**Comment by ecrouch** [comment] 2016-07-29 17:20
@shiona with Grunt running, the map has re-appeared and is functional. Thanks for filling me in. I'm still dropping data with 3 threads per account though, I wonder why I have to run 6 rather than 9...

**Comment by Paralysing** [comment] 2016-07-29 17:32
I doubt they would add up throttling, if multiple people use the same hotspot or wifi network, their ip's would be the same, and throttles would then apply to normal players.

**Comment by WaeCo** [comment] 2016-07-30 05:55
How about putting an login in the front end and enable users to user their own accounts?

This would require some kind of session management.
Users should be able to see scanned Pokemon of other but can only move their own scan location.

**Comment by Paralysing** [comment] 2016-07-30 06:00
@WaeCo That is a possibility, but it seems like the developers of this project currently don't want to implement session management. Look at #2179

**Comment by Paralysing** [comment] 2016-07-31 01:14
We may have another issue, Niantic seems like it now throttles to 1 request every 5 seconds. Look at #2774 for more info.

**Comment by Dragonprovidence** [comment] 2016-07-31 01:20
Oh forreals? That's interesting. That would be pretty rough. So far, my three  servers haven't seen any issues at -t 3 -st 6 -sd 1, but I'll keep an eye on it.

**Comment by Dragonprovidence** [comment] 2016-07-31 01:22
Ah, just read the other treads about the minimum scan for new pokemon. That's rough.

**Comment by wolf5x** [comment] 2016-07-31 01:23
I tested with 100 accounts. It happened twice that some ptc logins returned 403 with correct username/password. I'm not sure why it happened, but it may be good to skip the account after it fails for some times instead of infinite retry.

**Comment by turtle2472** [comment] 2016-07-31 01:28
I am seeing the error on all my accounts at this time.  I just created a new account and it was immediately given the 403. I hope this is short term, though there was a recent article from Niantic CEO (IIRC) that they see maps as cheating and will stop them.

**Comment by shiona** [comment] 2016-07-31 15:00
I just made a major commit. 
It breaks the way authentication was given for multiple accounts, in favor of keeping
backwards compatibility with upstream. 

Now it assumes one or more `-a`, `-u` and `-p` flags. If just one `-a` or `-p` is given then
that single one is used for every username.

More information is available in the commit message.

**Comment by photex12** [comment] 2016-07-31 16:28
@shiona Works like a charm :dancer: 
Just another question.
How can I configure the server to accept multiple users.

As it is if one user changes location, everyone goes to that location.

**Comment by shiona** [comment] 2016-07-31 16:47
@photex12 For me it just works.

**Comment by photex12** [comment] 2016-07-31 16:51
@shiona Might I be doing something wrong?
When i'm setting to location A and a friend in mine is changing location to B the moment I refresh the page I find myself looking at location B....

**Comment by shiona** [comment] 2016-07-31 16:54
ah, well that's a completely different thing. For that you'll just want to be scanning two different places with two runserver.py processes.

I thought that you meant that moving to another location didn't move some of the scanning threads, which would be a bug.

**Comment by Ashex** [comment] 2016-07-31 16:55
Seems the more we build the project to workaround issues like this, the more likely Niantic will shutdown the project as this feature directly circumvents server side protections.

As far as going with the worker method, I wrote a short python script for launching all my workers using docker.

```python
#!/usr/bin/env python
import subprocess

account_args = []
docker_runs = []

# Simple text file containing a list of space delimited
# credentials in "user password" form
with open("pgo_accounts.txt") as f:
    for line in f:
        (key, val) = line.split()
        account_args.append('--user="{user}" '
                            '--password="{password}"'.format(user=key,
                                                             password=val)
                            )

with open("locations.txt") as f:
    for line, user in zip(f, account_args):
        location = '--location "{0}"'.format(line.strip('\n'))
        docker_runs.append(
            'docker run -d --env-file ~/env.list --link mariadb '
            '--label type="worker" ashex/pokemongo-map:latest '
            '--no-server {location} {creds}'.format(
                                                    location=location,
                                                    creds=user)
        )

for run in docker_runs:
    print subprocess.Popen(run,
                            shell=True, stdout=subprocess.PIPE).stdout.read()

```

**Comment by photex12** [comment] 2016-07-31 19:09
hmmm now i keep getting this message on just one of the servers "OperationalError: database is locked"

**Comment by Paralysing** [comment] 2016-07-31 19:26
@photex12 Try rebooting the server you are running the map on, it fixed the issue for me.

**Comment by photex12** [comment] 2016-07-31 19:31
@Paralysing fixed it. well sort of.
Changed the portnumber this server was running on and that fixed the problem.
Will reboout tonight.

**Comment by hagehg** [comment] 2016-07-31 20:13
So i just got the latest build from the develop  branch and set it up to run on two accounts, but what do I do now to take advantage of that?

I have been running -sd 5 -t 1

Do you double the threads to two or cut the scan delay in half or something else? Thanks!

**Comment by Paralysing** [comment] 2016-07-31 20:16
@hagehg For me, I run 5 accounts on -t 5 -sd 5.1, it does speed up scanning. Basically, you could scale -t to the number of accounts, in your case -t 2 -sd 5.1

**Comment by AHAAAAAAA** [comment] 2016-07-31 20:19
@apazzy it's -u user1 -u user2 -p pass1 -p pass2

**Closed** 2016-07-31 20:19 UTC

**Comment by photex12** [comment] 2016-07-31 21:21
Again the same server error....
I've got 5 x runserver.py running, all with different acounts and in different folder, thus different databases.
Only one of the runserver.py keeps giving this error.
Deleted the broken down server, made a new one and again that same server brakes down.
The other 4 keep running without trouble.
