### ISSUE TITLE
Dev: TypeError: 'ResultIterator' object is not iterable`

### ISSUE THREAD

**Issue by SeeingBlue** [AHAAAAAAA/PokemonGo-Map#829] opened 2016-07-21 11:42 UTC
Updated to latest build this morning(#570)

```
2016-07-21 07:39:50,117 [     models] [   INFO] Get Pokemons for stamp: 2016-07-21 07:39:37.793000
[2016-07-21 07:39:50,125] ERROR in app: Exception on /gyms [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\pogom\app.py", line 49, in gyms
    return jsonify([g for g in Gym.select().dicts()])
  File "C:\Python27\lib\site-packages\peewee.py", line 2047, in next
    obj = self.qrw.iterate()
  File "C:\Python27\lib\site-packages\peewee.py", line 2107, in iterate
    return self.process_row(row)
  File "C:\Python27\lib\site-packages\peewee.py", line 2196, in process_row
    res[column] = func(row[i])
  File "C:\Python27\lib\site-packages\peewee.py", line 1134, in python_value
    return format_date_time(value, self.formats)
  File "C:\Python27\lib\site-packages\peewee.py", line 180, in format_date_time
    return post_process(datetime.datetime.strptime(value, fmt))
AttributeError: _strptime
2016-07-21 07:39:50,131 [  _internal] [   INFO] 127.0.0.1 - - [21/Jul/2016 07:39:50] "GET /pokemons/1469101177793 HTTP/1.1" 200 -
2016-07-21 07:39:50,125 [        app] [  ERROR] Exception on /gyms [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\pogom\app.py", line 49, in gyms
    return jsonify([g for g in Gym.select().dicts()])
  File "C:\Python27\lib\site-packages\peewee.py", line 2047, in next
    obj = self.qrw.iterate()
  File "C:\Python27\lib\site-packages\peewee.py", line 2107, in iterate
    return self.process_row(row)
  File "C:\Python27\lib\site-packages\peewee.py", line 2196, in process_row
    res[column] = func(row[i])
  File "C:\Python27\lib\site-packages\peewee.py", line 1134, in python_value
    return format_date_time(value, self.formats)
  File "C:\Python27\lib\site-packages\peewee.py", line 180, in format_date_time
    return post_process(datetime.datetime.strptime(value, fmt))
AttributeError: _strptime
[2016-07-21 07:39:50,125] ERROR in app: Exception on /pokestops [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\pogom\app.py", line 45, in pokestops
    return jsonify(Pokestop.get())
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 203, in encode
    chunks = list(chunks)
  File "C:\Python27\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\pogom\app.py", line 80, in default
    return list(iterable)
TypeError: 'ResultIterator' object is not iterable
2016-07-21 07:39:50,125 [        app] [  ERROR] Exception on /pokestops [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\pogom\app.py", line 45, in pokestops
    return jsonify(Pokestop.get())
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 203, in encode
    chunks = list(chunks)
  File "C:\Python27\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\pogom\app.py", line 80, in default
    return list(iterable)
TypeError: 'ResultIterator' object is not iterable
```

**Comment by RyanMBlue** [comment] 2016-07-21 11:51
Duplicate of #790

**Closed** 2016-07-21 12:10 UTC
Labels: duplicate
