### ISSUE TITLE
Not all Pokemon shown

### ISSUE THREAD

**Issue by Mzeus93** [AHAAAAAAA/PokemonGo-Map#1962] opened 2016-07-25 08:14 UTC
## Expected Behavior
All the Pokemon in the area have to be shown in the map, or at least all the Pokemon shawn in the site pokevision.com have to be shown also in the map generate from this program.

## Current Behavior
Making a comparison between pokemon shown in Pokevision.com and the one shown by this program i noticed that not all the pokemon are shown, i removed all the filter from both the apps and I used a step limit of 10.

## Steps to Reproduce (for bugs)
1. select an adress
2. open pokevision.com and make a scan in this area
3. launch this program from the bash with the same adress
4. you'll see some differences between pokemon found in the maps

## Your Environment
* Version used: v2.0.0
* Python 2.7
* Windows 10, Windows 7

**Comment by andrewda** [comment] 2016-07-25 08:21
This is a duplicate of probably at least 15 other issues (most recently #1944). Please use the search before creating a new issue.

**Closed by andrewda** 2016-07-25 08:21 UTC
