### ISSUE TITLE
SQL issue

### ISSUE THREAD

**Issue by tedlasai** [AHAAAAAAA/PokemonGo-Map#867] opened 2016-07-21 13:38 UTC
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: MAC OSX 10.11.5

Installed version of Python: 2.7

### Steps to reproduce
1.python runserver.py -a ptc -u ****** -p ***** -l "Times Square" -st 5
2. logs in. Then i get this issue
3.

### What have you tried?
1.

### Logs or other output that would be helpful
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/saitedla/Downloads/PokemonGo-Map-develop/pogom/search.py", line 94, in search_loop
    search(args)
  File "/Users/saitedla/Downloads/PokemonGo-Map-develop/pogom/search.py", line 83, in search
    parse_map(response_dict)
  File "/Users/saitedla/Downloads/PokemonGo-Map-develop/pogom/models.py", line 178, in parse_map
    InsertQuery(Pokestop, rows=pokestops.values()).upsert().execute()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: too many SQL variables

**Comment by Bakies** [comment] 2016-07-21 13:41
does deleting pogom.db fix this?

**Comment by benemorius** [comment] 2016-07-21 13:43
No. This is caused by encountering a cell with a large number of pokestops and trying to insert them all into the database.

**Comment by benemorius** [comment] 2016-07-21 13:46
It appears fixed as of df8b8665ced0ed91a6c43dc02795838ca2c77b62

**Comment by DerScreever** [comment] 2016-07-21 13:48
for me its fixed :D

**Closed** 2016-07-21 22:10 UTC
Labels: bug
