### ISSUE TITLE
Toggling the Pokemon visibility switch doesn't hide lured pokemon

### ISSUE THREAD

**Issue by invisiblek** [AHAAAAAAA/PokemonGo-Map#2329] opened 2016-07-27 15:02 UTC

**Comment by hgentry** [comment] 2016-07-27 15:12
I actually coded a fix for this last night, didn't have time to test before work due to grunt install taking several hours.

**Comment by hgentry** [comment] 2016-07-27 15:13
I haven't tested this, but replace the last chunk of map.js with this:

`    function buildSwitchChangeListener(data, data_type, storageKey) {
        return function () {
            Store.set(storageKey, this.checked);
            if (this.checked) {
                updateMap();
            } else {
                $.each(data[data_type], function (key, value) {
                    data[data_type][key].marker.setMap(null);
                });
                data[data_type] = {}
            }
        }
    }

    function buildSwitchChangeListener2(data, data_type1, data_type2, storageKey) {
        return function () {
            Store.set(storageKey, this.checked);
            if (this.checked) {
                updateMap();
            } else {
                console.log("After party");
                $.each(data[data_type1], function (key, value) {
                    data[data_type1][key].marker.setMap(null);
                });
                $.each(data[data_type2], function (key, value) {
                    data[data_type2][key].marker.setMap(null);
                });
                data[data_type1] = {}
                data[data_type2] = {}
            }
        }
    }

    // Setup UI element interactions
    $('#gyms-switch').change(buildSwitchChangeListener(map_data, "gyms", "showGyms"));
    $('#pokemon-switch').change(buildSwitchChangeListener2(map_data, "pokemons", "lure_pokemons", "showPokemon"));
    $('#pokestops-switch').change(buildSwitchChangeListener(map_data, "pokestops", "showPokestops"));
    $('#scanned-switch').change(buildSwitchChangeListener(map_data, "scanned", "showScanned"));

    $('#sound-switch').change(function() {
        Store.set("playSound", this.checked);
    });

    $('#pokemon-icons').change(function() {
        Store.set('pokemonIcons', this.value);
        redrawPokemon(map_data.pokemons);
        redrawPokemon(map_data.lure_pokemons);
    });

    $('#pokemon-icon-size').change(function() {
        Store.set('iconSizeModifier', this.value);
        redrawPokemon(map_data.pokemons);
        redrawPokemon(map_data.lure_pokemons);
    });

    $('#geoloc-switch').change(function() {  
        if(!navigator.geolocation)  
            this.checked = false;  
        else   
            Store.set('geoLocate', this.checked);
    });

});`

**Comment by PiaFraus** [comment] 2016-07-27 15:15
Actually I might've fixed as a side change in #2131 . Line 815

**Comment by invisiblek** [comment] 2016-07-27 15:15
was just adding this as a reminder for myself to fix it, feel free to submit a PR and ping me on it

**Comment by hgentry** [comment] 2016-07-27 16:18
grunt is now performing its 30-minute dance with babel...

**Comment by hgentry** [comment] 2016-07-27 16:25
Code change works, confirmed. Grunt still isn't done, though. Will PR whenever it finishes.

**Comment by invisiblek** [comment] 2016-07-27 16:26
what about something like this? https://gist.github.com/invisiblek/b0fafbeddaaf87891029ef5ffe8d82b8

**Closed** 2016-07-28 01:51 UTC
Labels: bug
