### ISSUE TITLE
Scanned are slowly drifts away from starting location.

### ISSUE THREAD

**Issue by nborrmann** [AHAAAAAAA/PokemonGo-Map#231] opened 2016-07-19 01:25 UTC
I started at the red marker on the top left corner, the scanned are slowly walked into south-east direction away from the starting point.

![image](https://cloud.githubusercontent.com/assets/1723176/16935494/3bfcbc0c-4d60-11e6-934f-09bd5b08dcc7.png)

I used the `-l "Streetname, City"` option for setting the location.

**Comment by JZ6** [comment] 2016-07-19 01:42
whats your steps?

**Comment by nborrmann** [comment] 2016-07-19 01:43
it was 4 in the pc, but it doesnt matter.

**Comment by timbennett** [comment] 2016-07-19 01:52
Duplicate of #202

**Comment by macgngsta** [comment] 2016-07-19 01:57
can confirm. it seems that the start of the next scan takes the last scanned coordinate, instead of the origin coordinates. ill have to check the code to make sure my hypothesis is correct

![pokedrift](https://cloud.githubusercontent.com/assets/1333829/16936146/4da668b4-4d19-11e6-98a5-c6f4fbfbcd03.jpg)

**Comment by nickgarvey** [comment] 2016-07-19 02:17
These are global variables and are shared across threads. That's probably the problem. Use a thread local variable instead:
https://docs.python.org/2/library/threading.html#threading.local

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/example.py#L191

**Comment by amal** [comment] 2016-07-19 02:39
@nickgarvey we can just reset location to original at the end of looping steps – it's already enough. see #239

**Comment by nickgarvey** [comment] 2016-07-19 02:40
Yup, makes sense.

**Closed** 2016-07-19 03:21 UTC
