### ISSUE TITLE
Barely any pokemon are showing

### ISSUE THREAD

**Issue by InstallGentoo11** [AHAAAAAAA/PokemonGo-Map#1636] opened 2016-07-23 20:52 UTC
After the newest version with the new options and stuff I barely get any pokemon showing around. Even pokevision is now showing me more than this. I am using Python 2.7 and a Windows 7 PC.

**Comment by Secret0tter** [comment] 2016-07-23 20:55
Me and many other users were having this problem. Adding "-t 1" to the end of your command chain should fix it. It did for me. It will slow down the search though.

**Comment by callmeron** [comment] 2016-07-23 20:55
See #1540 for discussion about this. I would close this out as a dupe of the referenced Issues.

**Closed** 2016-07-23 21:01 UTC
