### ISSUE TITLE
Login should be handled concurrently

### ISSUE THREAD

**Issue by moddyz** [AHAAAAAAA/PokemonGo-Map#2976] opened 2016-08-01 10:28 UTC
I've created 40 PTC accounts, but the login process is too slow.  

## Expected Behavior
The logging in should be handled concurrently, to drastically speed up the login time for multiple accounts

## Current Behavior
The accounts are being logged in one at a time.    Each login takes like 3-4 seconds, multiply that by # of accounts 😦 

## Possible Solution
A threaded map would do the trick 

## Steps to Reproduce (for bugs)
1. Create multiple PTC accounts
2. Use the multiple PTC accounts to run the server

## Context
Logging in is a bottle neck!

## Your Environment

* Version used: develop branch (a83ce5c0e6bfa4a97df485498e27fe3a0181ef7a)
* Environment name and version (e.g. Python 2.7): 2.7.10
* Operating System and version (desktop or mobile): OSX

**Comment by Frozen-byte** [comment] 2016-08-01 10:53
duplicate of #2908 I guess?

**Comment by moddyz** [comment] 2016-08-01 11:22
ur right!

**Closed** 2016-08-01 11:23 UTC
