### ISSUE TITLE
After half an hour of work on the map no longer appear new Pokémon

### ISSUE THREAD

**Issue by EuRusik** [AHAAAAAAA/PokemonGo-Map#812] opened 2016-07-21 10:09 UTC
I have a bug, when i start server, his work good about half an hour. Then the old Pokémon gradually are disappearing, and new Pokemon do not appear on the map :( It is necessary to restart the server again.
http://imgur.com/a/AnRIc

**Comment by mherceg** [comment] 2016-07-21 10:11
I can verify the existance of the same problem. I wrote a bash script that restarts the server. Feel free to use:

#!/bin/bash
i=0
while [ $i -lt 1 ]
do
python runserver.py -a ptc -u xxxxxx -p xxxxxx -l xxxxxxxxxxxx -st 13 -P 80 -H 0.0.0.0 &
TASK_PID=$!
echo $TASK_PID
sleep 30m
kill $TASK_PID
done

**Comment by fettlaus** [comment] 2016-07-21 10:12
Possibly duplicate of #625

**Comment by AlphaJuliettOmega** [comment] 2016-07-21 10:30
had the same issue, probably Niantic blocking overly active movements by making the session invalid?
just stopping it and running it again works fine (basicaly re-logging in)

**Closed** 2016-07-21 10:51 UTC
Labels: duplicate
