### ISSUE TITLE
Pokemon no longer showing on the map

### ISSUE THREAD

**Issue by ExodusNZ** [AHAAAAAAA/PokemonGo-Map#3438] opened 2016-08-04 02:29 UTC
## Current Behavior

This was going last night Here is a small log file:

Am using the following code:

C:\Python27\python.exe C:\Users\User\Desktop\PokemonGo-Map-develop\runserver.py -a ptc -u user1 -p user1 -u -l "location" -st 10 -k key -nk -ng -sd 5.1 -H 0.0.0.0 -P 5000

2016-08-04 14:27:00,733 [ search_worker_5][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-04 14:27:00,756 [ search_worker_6][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-04 14:27:00,767 [ search_worker_4][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-04 14:27:00,778 [ search_worker_9][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-04 14:27:00,796 [ search_worker_2][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

## Possible Solution

Am not sure 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Windows 10 64Bit (Python 2.7)

**Comment by cdhowie** [comment] 2016-08-04 02:31
Duplicate of #3406

**Comment by gnu-user** [comment] 2016-08-04 02:31
I'm having the exact same issue, could be Niantic trying to put an end to external tools.

**Comment by flightcoin** [comment] 2016-08-04 02:32
Same issue for me as well. It just started.

**Comment by ExodusNZ** [comment] 2016-08-04 02:36
Ok sweet, glad it wasnt just me (Although wish it was so we could fix it!!), bloody niantic!

**Comment by flightcoin** [comment] 2016-08-04 02:42
If you want to keep updated, its here, but I am sure we will all see the updates later on.
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3406

**Comment by Tman1677** [comment] 2016-08-04 02:42
Definitely on niantics side, I'm having the same thing.

**Comment by Krydos1** [comment] 2016-08-04 02:43
I must be the only person in the world who searches for duplicate issues before posting. I'm a special and unique snowflake. :)

**Closed** 2016-08-04 02:44 UTC
