### ISSUE TITLE
Hex Generator Not Evenly Generating?

### ISSUE THREAD

**Issue by DeviantEng** [AHAAAAAAA/PokemonGo-Map#2621] opened 2016-07-29 16:14 UTC
Latest dev build on Linux.  

Used this to generate my beehive.sh:
`python location_generator.py -lat "37.674221" -lon "-82.777588" -st 3 -lp 5 --accounts=/opt/PokemonGo-Map/accounts.csv`

Here is what I'm getting:
http://imgur.com/a/avNdT

I'm using 10 PTC accounts to distribute the load.  Using `-st 5 -lp 3` is still not showing up as expected.  Did I do something wrong?

**Comment by hgentry** [comment] 2016-07-29 16:42
Are you sure you're fully updated? A fix for this went out three hours ago.

**Comment by DeviantEng** [comment] 2016-07-29 16:49
Yes, I am running commit `0eb3c9bc0afcefc829d8d50ce3ab1200bfd9ce64`, which is currently the latest, with PR #2597.

**Comment by DeviantEng** [comment] 2016-07-29 20:18
Updated to the latest develop build, `681580a`, and still seeing weird behavior.

`-st 3 -lp 3` is giving me this:
http://imgur.com/a/RqHR2

**Comment by hgentry** [comment] 2016-07-29 20:34
I'm having issues, too. I think I've figured out the cause and will be updating it soon

**Comment by ChopSu3y** [comment] 2016-07-29 21:14
Has a method for adding multiple accounts to the bash script been found? If so, how is it done?

**Closed** 2016-08-02 15:35 UTC
