### ISSUE TITLE
Map download Failed. Try again.

### ISSUE THREAD

**Issue by ditran93** [AHAAAAAAA/PokemonGo-Map#675] opened 2016-07-20 21:59 UTC
I got this error. Can someone help me with this? 
![1](https://cloud.githubusercontent.com/assets/17958135/17004605/540a7028-4e9b-11e6-82e0-15033461d4ec.jpg)

**Comment by Bakies** [comment] 2016-07-20 22:00
I think this is niantics servers fault

**Comment by Stex** [comment] 2016-07-20 22:01
@ditran93 This is most likely caused by the server problems Pokémon GO currently experiences. 

See http://ispokemongodownornot.com/ for more information about this.

**Comment by ditran93** [comment] 2016-07-20 22:04
Got it! Thanks guys!

**Comment by medghaim** [comment] 2016-07-20 23:13
Closing as it's not an issue.

**Closed by medghaim** 2016-07-20 23:13 UTC
Labels: Not an issue: servers are down
